package main

import (
	"bufio"
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestFilterCoverageData_FiltersGeneratedFiles(t *testing.T) {
	repoRoot := t.TempDir()
	modulePrefix := "github.com/equaltoai/lesser/"

	require.NoError(t, os.MkdirAll(filepath.Join(repoRoot, "pkg"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(repoRoot, "pkg", "foo.go"), []byte("package foo\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(repoRoot, "pkg", "generated.go"), []byte("// Code generated by tests. DO NOT EDIT.\npackage foo\n"), 0o644))

	in := strings.Join([]string{
		"mode: set",
		modulePrefix + "pkg/foo.go:1.1,2.1 1 1",
		modulePrefix + "pkg/generated.go:1.1,2.1 1 1",
		"weird line with no colon",
		"",
	}, "\n")

	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)
	require.NoError(t, filterCoverageData(strings.NewReader(in), w, repoRoot, modulePrefix))
	require.NoError(t, w.Flush())

	out := buf.String()
	require.Contains(t, out, modulePrefix+"pkg/foo.go:")
	require.NotContains(t, out, modulePrefix+"pkg/generated.go:")
	require.Contains(t, out, "weird line with no colon")
}

func TestFilterGeneratedFilesFromCoverProfile_RemovesGeneratedEntries(t *testing.T) {
	repoRoot := t.TempDir()
	modulePrefix := "github.com/equaltoai/lesser/"

	require.NoError(t, os.WriteFile(filepath.Join(repoRoot, "go.mod"), []byte("module github.com/equaltoai/lesser\n"), 0o644))
	require.NoError(t, os.MkdirAll(filepath.Join(repoRoot, "pkg"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(repoRoot, "pkg", "foo.go"), []byte("package foo\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(repoRoot, "pkg", "generated.go"), []byte("// Code generated. DO NOT EDIT.\npackage foo\n"), 0o644))

	coverProfilePath := filepath.Join(repoRoot, "coverage.out")
	require.NoError(t, os.WriteFile(coverProfilePath, []byte(strings.Join([]string{
		"mode: set",
		modulePrefix + "pkg/foo.go:1.1,2.1 1 1",
		modulePrefix + "pkg/generated.go:1.1,2.1 1 1",
		"",
	}, "\n")), 0o644))

	require.NoError(t, filterGeneratedFilesFromCoverProfile(repoRoot, coverProfilePath))

	out, err := os.ReadFile(coverProfilePath)
	require.NoError(t, err)
	require.Contains(t, string(out), modulePrefix+"pkg/foo.go:")
	require.NotContains(t, string(out), modulePrefix+"pkg/generated.go:")
}

func TestIsGeneratedFile_FalseWhenUnreadable(t *testing.T) {
	require.False(t, isGeneratedFile(t.TempDir(), "github.com/equaltoai/lesser/", "github.com/equaltoai/lesser/pkg/missing.go"))
}

func TestListPackagesForPkgCoverage_FiltersPkgTesting(t *testing.T) {
	previousCapture := captureCommandOutputFn
	t.Cleanup(func() { captureCommandOutputFn = previousCapture })

	repoRoot := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(repoRoot, "go.mod"), []byte("module github.com/equaltoai/lesser\n"), 0o644))

	captureCommandOutputFn = func(context.Context, string, map[string]string, string, ...string) (string, error) {
		return strings.Join([]string{
			"github.com/equaltoai/lesser/pkg/a",
			"github.com/equaltoai/lesser/pkg/testing/harness",
			"github.com/equaltoai/lesser/pkg/z",
		}, "\n"), nil
	}

	pkgs, err := listPackagesForPkgCoverage(repoRoot, t.TempDir())
	require.NoError(t, err)
	require.Equal(t, []string{
		"github.com/equaltoai/lesser/pkg/a",
		"github.com/equaltoai/lesser/pkg/z",
	}, pkgs)
}
