package errors

import (
	stdErrors "errors"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestLambdaConstructors_ExhaustiveCoverage(t *testing.T) {
	boom := stdErrors.New("boom")

	constructors := []struct {
		name string
		fn   func() *AppError
	}{
		{name: "NewLambdaError", fn: func() *AppError { return NewLambdaError(CodeInternal, "msg") }},
		{name: "NewLambdaInternalError", fn: func() *AppError { return NewLambdaInternalError(CodeInternal, "msg", boom) }},
		{name: "LambdaTimeout", fn: func() *AppError { return LambdaTimeout("fn") }},
		{name: "LambdaColdStart", fn: func() *AppError { return LambdaColdStart("fn", 123) }},
		{name: "LambdaMemoryExceeded", fn: func() *AppError { return LambdaMemoryExceeded("fn", 128) }},
		{name: "LambdaInitializationFailed", fn: func() *AppError { return LambdaInitializationFailed("fn", boom) }},
		{name: "LambdaConfigurationError", fn: func() *AppError { return LambdaConfigurationError("fn", "setting") }},
		{name: "SQSMessageInvalid", fn: func() *AppError { return SQSMessageInvalid("mid", "reason") }},
		{name: "SQSMessageProcessingFailed", fn: func() *AppError { return SQSMessageProcessingFailed("mid", boom) }},
		{name: "SQSBatchProcessingFailed", fn: func() *AppError { return SQSBatchProcessingFailed(10, 9, boom) }},
		{name: "SQSMessageTooLarge", fn: func() *AppError { return SQSMessageTooLarge(123) }},
		{name: "SQSVisibilityTimeoutExceeded", fn: func() *AppError { return SQSVisibilityTimeoutExceeded("mid") }},
		{name: "SQSRetryExhausted", fn: func() *AppError { return SQSRetryExhausted("mid", 3) }},
		{name: "DLQMessageSendFailed", fn: func() *AppError { return DLQMessageSendFailed("mid", boom) }},
		{name: "DLQProcessingFailed", fn: func() *AppError { return DLQProcessingFailed("mid", boom) }},
		{name: "DLQRetryExhausted", fn: func() *AppError { return DLQRetryExhausted("mid", 3) }},
		{name: "EventProcessingFailed", fn: func() *AppError { return EventProcessingFailed("type", boom) }},
		{name: "EventInvalid", fn: func() *AppError { return EventInvalid("type", "reason") }},
		{name: "EventMissingField", fn: func() *AppError { return EventMissingField("type", "field") }},
		{name: "EventTooLarge", fn: func() *AppError { return EventTooLarge("type", 123) }},
		{name: "EventParsingFailed", fn: func() *AppError { return EventParsingFailed("type", boom) }},
		{name: "StreamRecordInvalid", fn: func() *AppError { return StreamRecordInvalid("rid", "reason") }},
		{name: "StreamRecordProcessingFailed", fn: func() *AppError { return StreamRecordProcessingFailed("rid", boom) }},
		{name: "StreamNewImageMissing", fn: func() *AppError { return StreamNewImageMissing("rid") }},
		{name: "StreamOldImageMissing", fn: func() *AppError { return StreamOldImageMissing("rid") }},
		{name: "StreamUnmarshalFailed", fn: func() *AppError { return StreamUnmarshalFailed("rid", "new", boom) }},
		{name: "ActivityRecordUnmarshalFailed", fn: func() *AppError { return ActivityRecordUnmarshalFailed(boom) }},
		{name: "ActivityObjectProcessingFailed", fn: func() *AppError { return ActivityObjectProcessingFailed("Create", boom) }},
		{name: "BatchHasRetryableErrors", fn: func() *AppError { return BatchHasRetryableErrors(1) }},
		{name: "BatchPartialSuccess", fn: func() *AppError { return BatchPartialSuccess(1, 2) }},
		{name: "TimelineRemovalFailed", fn: func() *AppError { return TimelineRemovalFailed("actor", boom) }},
		{name: "TimelineEntriesCreationFailed", fn: func() *AppError { return TimelineEntriesCreationFailed(boom) }},
		{name: "TimelineEntriesWriteFailed", fn: func() *AppError { return TimelineEntriesWriteFailed(boom) }},
		{name: "WorkflowStepFailed", fn: func() *AppError { return WorkflowStepFailed("step", boom) }},
		{name: "WorkflowInvalidState", fn: func() *AppError { return WorkflowInvalidState("state") }},
		{name: "WorkflowTimeout", fn: func() *AppError { return WorkflowTimeout("wf", 123) }},
		{name: "EnvironmentVariableMissing", fn: func() *AppError { return EnvironmentVariableMissing("VAR") }},
		{name: "ServiceInitializationFailed", fn: func() *AppError { return ServiceInitializationFailed("svc", boom) }},
		{name: "ResourceAccessDenied", fn: func() *AppError { return ResourceAccessDenied("res") }},
		{name: "ExternalServiceUnavailable", fn: func() *AppError { return ExternalServiceUnavailable("svc", boom) }},
		{name: "ObjectMarshalingFailed", fn: func() *AppError { return ObjectMarshalingFailed("obj", boom) }},
		{name: "ObjectUnmarshalingFailed", fn: func() *AppError { return ObjectUnmarshalingFailed("obj", boom) }},
		{name: "ObjectValidationFailed", fn: func() *AppError { return ObjectValidationFailed("obj", "reason") }},
		{name: "NotificationProcessingFailed", fn: func() *AppError { return NotificationProcessingFailed("type", boom) }},
		{name: "PushDeliveryFailed", fn: func() *AppError { return PushDeliveryFailed("device", boom) }},
		{name: "CostTrackingInitFailed", fn: func() *AppError { return CostTrackingInitFailed(boom) }},
		{name: "CostLimitApproaching", fn: func() *AppError { return CostLimitApproaching("fn", 1.0, 2.0) }},
		{name: "SearchIndexingFailed", fn: func() *AppError { return SearchIndexingFailed("type", boom) }},
		{name: "StatusIndexingFailed", fn: func() *AppError { return StatusIndexingFailed("id", boom) }},
		{name: "MediaProcessingFailed", fn: func() *AppError { return MediaProcessingFailed("video", boom) }},
		{name: "MediaJobFailed", fn: func() *AppError { return MediaJobFailed("job", boom) }},
		{name: "ModerationProcessingFailed", fn: func() *AppError { return ModerationProcessingFailed("content", boom) }},
		{name: "TrendAggregationFailed", fn: func() *AppError { return TrendAggregationFailed("trend", boom) }},
		{name: "MetricsProcessingFailed", fn: func() *AppError { return MetricsProcessingFailed("metric", boom) }},
		{name: "WebSocketCostAggregationFailed", fn: func() *AppError { return WebSocketCostAggregationFailed(boom) }},
		{name: "StreamRouterFailed", fn: func() *AppError { return StreamRouterFailed("type", boom) }},
		{name: "StreamingEventProcessingFailed", fn: func() *AppError { return StreamingEventProcessingFailed("type", boom) }},
		{name: "StreamingInvalidMessageFormat", fn: func() *AppError { return StreamingInvalidMessageFormat() }},
		{name: "StreamingConnectionNotFound", fn: func() *AppError { return StreamingConnectionNotFound() }},
		{name: "StreamingUnknownMessageType", fn: func() *AppError { return StreamingUnknownMessageType() }},
		{name: "StreamingInvalidStream", fn: func() *AppError { return StreamingInvalidStream() }},
		{name: "StreamingAuthenticationRequired", fn: func() *AppError { return StreamingAuthenticationRequired() }},
		{name: "StreamingFailedToSubscribe", fn: func() *AppError { return StreamingFailedToSubscribe() }},
		{name: "StreamingFailedToUnsubscribe", fn: func() *AppError { return StreamingFailedToUnsubscribe() }},
		{name: "StreamingInvalidCommandFormat", fn: func() *AppError { return StreamingInvalidCommandFormat() }},
		{name: "StreamingCommandExecutionFailed", fn: func() *AppError { return StreamingCommandExecutionFailed() }},
		{name: "StreamingUnknownRoute", fn: func() *AppError { return StreamingUnknownRoute() }},
		{name: "WebSocketCostAllAlertMethodsFailed", fn: func() *AppError { return WebSocketCostAllAlertMethodsFailed() }},
		{name: "WebSocketCostMarshalAlertMessage", fn: func() *AppError { return WebSocketCostMarshalAlertMessage() }},
		{name: "WebSocketCostGetIdleConnections", fn: func() *AppError { return WebSocketCostGetIdleConnections() }},
		{name: "WebSocketCostGetHighCostUsers", fn: func() *AppError { return WebSocketCostGetHighCostUsers() }},
		{name: "WebSocketCostGetStaleConnections", fn: func() *AppError { return WebSocketCostGetStaleConnections() }},
		{name: "WebSocketCostPublishSNSMessage", fn: func() *AppError { return WebSocketCostPublishSNSMessage() }},
		{name: "WebSocketCostCreateWebhookRequest", fn: func() *AppError { return WebSocketCostCreateWebhookRequest() }},
		{name: "WebSocketCostWebhookRequestFailed", fn: func() *AppError { return WebSocketCostWebhookRequestFailed() }},
		{name: "WebSocketCostWebhookNon2xxStatus", fn: func() *AppError { return WebSocketCostWebhookNon2xxStatus() }},
		{name: "WebSocketCostTrackIdleConnections", fn: func() *AppError { return WebSocketCostTrackIdleConnections() }},
		{name: "NoteProcessorPartialBatchFailure", fn: func() *AppError { return NoteProcessorPartialBatchFailure() }},
		{name: "NoteProcessorGetNote", fn: func() *AppError { return NoteProcessorGetNote() }},
		{name: "NoteProcessorGetVotes", fn: func() *AppError { return NoteProcessorGetVotes() }},
		{name: "NoteProcessorUpdateNoteAnalysis", fn: func() *AppError { return NoteProcessorUpdateNoteAnalysis() }},
		{name: "NoteProcessorUpdateNoteScore", fn: func() *AppError { return NoteProcessorUpdateNoteScore() }},
		{name: "NoteProcessorDetectSentiment", fn: func() *AppError { return NoteProcessorDetectSentiment() }},
		{name: "SearchIndexerPartialBatchFailure", fn: func() *AppError { return SearchIndexerPartialBatchFailure() }},
		{name: "SearchIndexerExtractIndexableContent", fn: func() *AppError { return SearchIndexerExtractIndexableContent() }},
		{name: "SearchIndexerUnmarshalStreamImage", fn: func() *AppError { return SearchIndexerUnmarshalStreamImage() }},
		{name: "SearchIndexerCreateSearchIndex", fn: func() *AppError { return SearchIndexerCreateSearchIndex() }},
		{name: "SearchIndexerStoreSearchIndex", fn: func() *AppError { return SearchIndexerStoreSearchIndex() }},
		{name: "SearchIndexerCreateActorSearchIndex", fn: func() *AppError { return SearchIndexerCreateActorSearchIndex() }},
		{name: "MetricsAggregatorMissingRequiredFields", fn: func() *AppError { return MetricsAggregatorMissingRequiredFields() }},
		{name: "MetricsAggregatorServiceStatsRetrieval", fn: func() *AppError { return MetricsAggregatorServiceStatsRetrieval() }},
		{name: "MetricsAggregatorAggregation", fn: func() *AppError { return MetricsAggregatorAggregation() }},
		{name: "MetricsAggregatorCleanup", fn: func() *AppError { return MetricsAggregatorCleanup() }},
		{name: "MetricsAggregatorStreamRecordUnmarshal", fn: func() *AppError { return MetricsAggregatorStreamRecordUnmarshal() }},
		{name: "FederationAggregatorAWSClientsInit", fn: func() *AppError { return FederationAggregatorAWSClientsInit() }},
		{name: "FederationAggregatorLambdaFunctionError", fn: func() *AppError { return FederationAggregatorLambdaFunctionError() }},
		{name: "FederationAggregatorLambdaInvocationFailed", fn: func() *AppError { return FederationAggregatorLambdaInvocationFailed() }},
		{name: "FederationAggregatorEventUnmarshal", fn: func() *AppError { return FederationAggregatorEventUnmarshal() }},
		{name: "FederationAggregatorEventMarshal", fn: func() *AppError { return FederationAggregatorEventMarshal() }},
		{name: "FederationAggregatorStore", fn: func() *AppError { return FederationAggregatorStore() }},
		{name: "FederationAggregatorActivitiesGet", fn: func() *AppError { return FederationAggregatorActivitiesGet() }},
		{name: "FederationAggregatorMessageProcessingFailed", fn: func() *AppError { return FederationAggregatorMessageProcessingFailed() }},
		{name: "EnhancedFederationProcessorDynamORMInit", fn: func() *AppError { return EnhancedFederationProcessorDynamORMInit() }},
		{name: "EnhancedFederationProcessorUnmarshalRetryMessage", fn: func() *AppError { return EnhancedFederationProcessorUnmarshalRetryMessage() }},
		{name: "EnhancedFederationProcessorProcessRetry", fn: func() *AppError { return EnhancedFederationProcessorProcessRetry() }},
		{name: "StatusIndexerPartialBatchFailure", fn: func() *AppError { return StatusIndexerPartialBatchFailure() }},
		{name: "StatusIndexerProcessStatusEvent", fn: func() *AppError { return StatusIndexerProcessStatusEvent() }},
		{name: "StatusIndexerNoNewImage", fn: func() *AppError { return StatusIndexerNoNewImage() }},
		{name: "StatusIndexerNoObjectData", fn: func() *AppError { return StatusIndexerNoObjectData() }},
		{name: "StatusIndexerCountReplies", fn: func() *AppError { return StatusIndexerCountReplies() }},
		{name: "FederationDeliveryInvalidMessageBody", fn: func() *AppError { return FederationDeliveryInvalidMessageBody() }},
		{name: "FederationDeliveryMessageMarshalFailure", fn: func() *AppError { return FederationDeliveryMessageMarshalFailure() }},
		{name: "FederationDeliveryMessageRequeueFailure", fn: func() *AppError { return FederationDeliveryMessageRequeueFailure() }},
		{name: "FederationDeliverySigningActorMissing", fn: func() *AppError { return FederationDeliverySigningActorMissing() }},
		{name: "FederationDeliveryMaxAttemptsExceeded", fn: func() *AppError { return FederationDeliveryMaxAttemptsExceeded() }},
		{name: "CostAggregatorAggregationFailed", fn: func() *AppError { return CostAggregatorAggregationFailed() }},
		{name: "CostAggregatorSNSMessageMarshal", fn: func() *AppError { return CostAggregatorSNSMessageMarshal() }},
		{name: "CostAggregatorSNSPublish", fn: func() *AppError { return CostAggregatorSNSPublish() }},
		{name: "CostAggregatorCloudWatchMetric", fn: func() *AppError { return CostAggregatorCloudWatchMetric() }},
		{name: "CostAggregatorEventMarshal", fn: func() *AppError { return CostAggregatorEventMarshal() }},
		{name: "CostAggregatorLambdaInvoke", fn: func() *AppError { return CostAggregatorLambdaInvoke() }},
		{name: "CostAggregatorLambdaFunctionError", fn: func() *AppError { return CostAggregatorLambdaFunctionError() }},
		{name: "AIProcessorContentExtractionFailed", fn: func() *AppError { return AIProcessorContentExtractionFailed() }},
		{name: "AIProcessorStreamUnmarshalFailed", fn: func() *AppError { return AIProcessorStreamUnmarshalFailed() }},
		{name: "AIProcessorInvalidObjectPK", fn: func() *AppError { return AIProcessorInvalidObjectPK() }},
		{name: "AIProcessorNotAnalyzableType", fn: func() *AppError { return AIProcessorNotAnalyzableType() }},
		{name: "AIProcessorAnalysisFailed", fn: func() *AppError { return AIProcessorAnalysisFailed() }},
		{name: "AIProcessorAnalysisSaveFailed", fn: func() *AppError { return AIProcessorAnalysisSaveFailed() }},
		{name: "TrendAggregatorHashtagRetrieval", fn: func() *AppError { return TrendAggregatorHashtagRetrieval() }},
		{name: "TrendAggregatorStatusRetrieval", fn: func() *AppError { return TrendAggregatorStatusRetrieval() }},
		{name: "TrendAggregatorLinkRetrieval", fn: func() *AppError { return TrendAggregatorLinkRetrieval() }},
		{name: "InitDeployFailedToCreateOrUpdateSecret", fn: func() *AppError { return InitDeployFailedToCreateOrUpdateSecret() }},
		{name: "InitDeployFailedToGeneratePrivateKey", fn: func() *AppError { return InitDeployFailedToGeneratePrivateKey() }},
		{name: "InitDeployFailedToMarshalPrivateKey", fn: func() *AppError { return InitDeployFailedToMarshalPrivateKey() }},
		{name: "InitDeployFailedToConvertToECDHKey", fn: func() *AppError { return InitDeployFailedToConvertToECDHKey() }},
		{name: "ReportTrustUpdaterMissingKeys", fn: func() *AppError { return ReportTrustUpdaterMissingKeys() }},
		{name: "ReportTrustUpdaterReportRetrieval", fn: func() *AppError { return ReportTrustUpdaterReportRetrieval() }},
	}

	for _, tc := range constructors {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.fn()
			assertAppErrorBasics(t, err)
			assert.Equal(t, CategoryLambda, err.Category)
		})
	}
}
