package errors

import (
	stdErrors "errors"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestAuthConstructors_ExhaustiveCoverage(t *testing.T) {
	boom := stdErrors.New("boom")

	constructors := []struct {
		name string
		fn   func() *AppError
	}{
		{name: "PasswordInsufficientLength", fn: func() *AppError { return PasswordInsufficientLength() }},
		{name: "PasswordSequentialPattern", fn: func() *AppError { return PasswordSequentialPattern() }},
		{name: "PasswordRepeatedPattern", fn: func() *AppError { return PasswordRepeatedPattern() }},
		{name: "CSRFTokenGenerationFailed", fn: func() *AppError { return CSRFTokenGenerationFailed(boom) }},
		{name: "SessionIDGenerationFailed", fn: func() *AppError { return SessionIDGenerationFailed(boom) }},
		{name: "CookieEntropyGenerationFailed", fn: func() *AppError { return CookieEntropyGenerationFailed(boom) }},
		{name: "CSRFTokenRotationFailed", fn: func() *AppError { return CSRFTokenRotationFailed(boom) }},
		{name: "CSRFValidationFailed", fn: func() *AppError { return CSRFValidationFailed() }},
		{name: "UnexpectedSigningMethod", fn: func() *AppError { return UnexpectedSigningMethod() }},
		{name: "SessionIDMismatch", fn: func() *AppError { return SessionIDMismatch() }},
		{name: "IPAddressMismatch", fn: func() *AppError { return IPAddressMismatch() }},
		{name: "TokenVersionMismatch", fn: func() *AppError { return TokenVersionMismatch() }},
		{name: "TokenTooOld", fn: func() *AppError { return TokenTooOld() }},
		{name: "NonceGenerationFailed", fn: func() *AppError { return NonceGenerationFailed(boom) }},
		{name: "ChallengeStorageFailed", fn: func() *AppError { return ChallengeStorageFailed(boom) }},
		{name: "ChallengeRetrievalFailed", fn: func() *AppError { return ChallengeRetrievalFailed(boom) }},
		{name: "MessageMismatch", fn: func() *AppError { return MessageMismatch() }},
		{name: "SignatureVerificationFailed", fn: func() *AppError { return SignatureVerificationFailed() }},
		{name: "WalletCheckFailed", fn: func() *AppError { return WalletCheckFailed(boom) }},
		{name: "WalletStorageFailed", fn: func() *AppError { return WalletStorageFailed(boom) }},
		{name: "WalletRetrievalFailed", fn: func() *AppError { return WalletRetrievalFailed(boom) }},
		{name: "WalletDeletionFailed", fn: func() *AppError { return WalletDeletionFailed(boom) }},
		{name: "InvalidSignatureFormat", fn: func() *AppError { return InvalidSignatureFormat() }},
		{name: "InvalidSignatureLength", fn: func() *AppError { return InvalidSignatureLength() }},
		{name: "PublicKeyRecoveryFailed", fn: func() *AppError { return PublicKeyRecoveryFailed(boom) }},
		{name: "SignatureAddressMismatch", fn: func() *AppError { return SignatureAddressMismatch() }},
		{name: "TrusteeActorIDRequired", fn: func() *AppError { return TrusteeActorIDRequired() }},
		{name: "RecoveryTokenGenerationFailed", fn: func() *AppError { return RecoveryTokenGenerationFailed(boom) }},
		{name: "RecoveryRequestNotPending", fn: func() *AppError { return RecoveryRequestNotPending() }},
		{name: "TrusteeStorageFailed", fn: func() *AppError { return TrusteeStorageFailed(boom) }},
		{name: "TrusteeDeletionFailed", fn: func() *AppError { return TrusteeDeletionFailed(boom) }},
		{name: "TrusteeRetrievalFailed", fn: func() *AppError { return TrusteeRetrievalFailed(boom) }},
		{name: "RecoveryRequestStorageFailed", fn: func() *AppError { return RecoveryRequestStorageFailed(boom) }},
		{name: "RecoveryRequestRetrievalFailed", fn: func() *AppError { return RecoveryRequestRetrievalFailed(boom) }},
		{name: "RecoveryRequestUpdateFailed", fn: func() *AppError { return RecoveryRequestUpdateFailed(boom) }},
		{name: "RecoveryTokenStorageFailed", fn: func() *AppError { return RecoveryTokenStorageFailed(boom) }},
		{name: "WebAuthnServiceInitFailed", fn: func() *AppError { return WebAuthnServiceInitFailed(boom) }},
		{name: "UserRetrievalFailed", fn: func() *AppError { return UserRetrievalFailed(boom) }},
		{name: "CredentialRetrievalFailed", fn: func() *AppError { return CredentialRetrievalFailed(boom) }},
		{name: "RegistrationBeginFailed", fn: func() *AppError { return RegistrationBeginFailed(boom) }},
		{name: "LoginBeginFailed", fn: func() *AppError { return LoginBeginFailed(boom) }},
		{name: "SessionDataSerializationFailed", fn: func() *AppError { return SessionDataSerializationFailed(boom) }},
		{name: "SessionDataDeserializationFailed", fn: func() *AppError { return SessionDataDeserializationFailed(boom) }},
		{name: "WebAuthnChallengeStorageFailed", fn: func() *AppError { return WebAuthnChallengeStorageFailed(boom) }},
		{name: "CredentialResponseParseFailed", fn: func() *AppError { return CredentialResponseParseFailed(boom) }},
		{name: "CredentialCreationFailed", fn: func() *AppError { return CredentialCreationFailed(boom) }},
		{name: "CredentialValidationFailed", fn: func() *AppError { return CredentialValidationFailed(boom) }},
		{name: "InvalidSessionDataType", fn: func() *AppError { return InvalidSessionDataType() }},
		{name: "RecoveryCodeGenerationFailed", fn: func() *AppError { return RecoveryCodeGenerationFailed(boom) }},
		{name: "RecoveryCodeHashingFailed", fn: func() *AppError { return RecoveryCodeHashingFailed(boom) }},
		{name: "RecoveryCodeStorageFailed", fn: func() *AppError { return RecoveryCodeStorageFailed(boom) }},
		{name: "RecoveryCodeRetrievalFailed", fn: func() *AppError { return RecoveryCodeRetrievalFailed(boom) }},
		{name: "RecoveryCodeMarkUsedFailed", fn: func() *AppError { return RecoveryCodeMarkUsedFailed(boom) }},
		{name: "RecoveryCodeClearFailed", fn: func() *AppError { return RecoveryCodeClearFailed(boom) }},
		{name: "AWSConfigLoadFailed", fn: func() *AppError { return AWSConfigLoadFailed(boom) }},
		{name: "SecretsManagerConnectionFailed", fn: func() *AppError { return SecretsManagerConnectionFailed(boom) }},
		{name: "InvalidPrivateKeyFormat", fn: func() *AppError { return InvalidPrivateKeyFormat() }},
		{name: "SecretValueMarshalFailed", fn: func() *AppError { return SecretValueMarshalFailed(boom) }},
		{name: "SecretCreationFailed", fn: func() *AppError { return SecretCreationFailed(boom) }},
		{name: "PrivateKeyRetrievalFailed", fn: func() *AppError { return PrivateKeyRetrievalFailed(boom) }},
		{name: "SecretValueUnmarshalFailed", fn: func() *AppError { return SecretValueUnmarshalFailed(boom) }},
		{name: "RetrievedPrivateKeyInvalid", fn: func() *AppError { return RetrievedPrivateKeyInvalid() }},
		{name: "SecretDeletionFailed", fn: func() *AppError { return SecretDeletionFailed(boom) }},
		{name: "RSAKeyPairGenerationFailed", fn: func() *AppError { return RSAKeyPairGenerationFailed(boom) }},
		{name: "PrivateKeyMarshalFailed", fn: func() *AppError { return PrivateKeyMarshalFailed(boom) }},
		{name: "PublicKeyMarshalFailed", fn: func() *AppError { return PublicKeyMarshalFailed(boom) }},
		{name: "GeneratedPrivateKeyStorageFailed", fn: func() *AppError { return GeneratedPrivateKeyStorageFailed(boom) }},
		{name: "KeyPairGenerationRotationFailed", fn: func() *AppError { return KeyPairGenerationRotationFailed(boom) }},
		{name: "PEMBlockDecodeFailed", fn: func() *AppError { return PEMBlockDecodeFailed() }},
		{name: "PrivateKeyParseFailed", fn: func() *AppError { return PrivateKeyParseFailed(boom) }},
		{name: "SecretValueNil", fn: func() *AppError { return SecretValueNil() }},
		{name: "SecretRetrievalRetriesFailed", fn: func() *AppError { return SecretRetrievalRetriesFailed(boom) }},
		{name: "AuditEventMarshalFailed", fn: func() *AppError { return AuditEventMarshalFailed(boom) }},
		{name: "SIEMRequestCreationFailed", fn: func() *AppError { return SIEMRequestCreationFailed(boom) }},
		{name: "SIEMTransmissionFailed", fn: func() *AppError { return SIEMTransmissionFailed(boom) }},
		{name: "SIEMResponseError", fn: func() *AppError { return SIEMResponseError() }},
		{name: "AuditRepositoryUnavailable", fn: func() *AppError { return AuditRepositoryUnavailable() }},
		{name: "IPRateLimitCheckFailed", fn: func() *AppError { return IPRateLimitCheckFailed(boom) }},
		{name: "AccountRateLimitCheckFailed", fn: func() *AppError { return AccountRateLimitCheckFailed(boom) }},
		{name: "RecordIPAttemptFailed", fn: func() *AppError { return RecordIPAttemptFailed(boom) }},
		{name: "RecordAccountAttemptFailed", fn: func() *AppError { return RecordAccountAttemptFailed(boom) }},
		{name: "GetIPAttemptCountFailed", fn: func() *AppError { return GetIPAttemptCountFailed(boom) }},
		{name: "GetAccountAttemptCountFailed", fn: func() *AppError { return GetAccountAttemptCountFailed(boom) }},
		{name: "ImposeIPLockoutFailed", fn: func() *AppError { return ImposeIPLockoutFailed(boom) }},
		{name: "ImposeAccountLockoutFailed", fn: func() *AppError { return ImposeAccountLockoutFailed(boom) }},
		{name: "RefreshTokenGenerationFailed", fn: func() *AppError { return RefreshTokenGenerationFailed(boom) }},
		{name: "DeviceIDRetrievalFailed", fn: func() *AppError { return DeviceIDRetrievalFailed(boom) }},
		{name: "NewRefreshTokenGenerationFailed", fn: func() *AppError { return NewRefreshTokenGenerationFailed(boom) }},
		{name: "SessionUpdateFailed", fn: func() *AppError { return SessionUpdateFailed(boom) }},
		{name: "UserSessionsRetrievalFailed", fn: func() *AppError { return UserSessionsRetrievalFailed(boom) }},
		{name: "OldestSessionRemovalFailed", fn: func() *AppError { return OldestSessionRemovalFailed(boom) }},
		{name: "UserDevicesRetrievalFailed", fn: func() *AppError { return UserDevicesRetrievalFailed(boom) }},
		{name: "DeviceCreationFailed", fn: func() *AppError { return DeviceCreationFailed(boom) }},
		{name: "JWTUnexpectedSigningMethod", fn: func() *AppError { return JWTUnexpectedSigningMethod() }},
		{name: "InvalidActivityObject", fn: func() *AppError { return InvalidActivityObject() }},
		{name: "NotRecoveryConfirmationActivity", fn: func() *AppError { return NotRecoveryConfirmationActivity() }},
		{name: "MissingRequestID", fn: func() *AppError { return MissingRequestID() }},
		{name: "FailedToDecodePEM", fn: func() *AppError { return FailedToDecodePEM() }},
		{name: "UnsupportedPrivateKeyType", fn: func() *AppError { return UnsupportedPrivateKeyType() }},
		{name: "SecretsManagerNotAvailable", fn: func() *AppError { return SecretsManagerNotAvailable() }},
		{name: "SigningActorRetrievalFailed", fn: func() *AppError { return SigningActorRetrievalFailed(boom) }},
		{name: "RecoveryConfirmationFailed", fn: func() *AppError { return RecoveryConfirmationFailed(boom) }},
		{name: "ActorRetrievalFailed", fn: func() *AppError { return ActorRetrievalFailed(boom) }},
		{name: "SystemActorKeyRetrievalFailed", fn: func() *AppError { return SystemActorKeyRetrievalFailed(boom) }},
		{name: "SystemActorKeyRotationFailed", fn: func() *AppError { return SystemActorKeyRotationFailed(boom) }},
		{name: "SessionMaxLifetimeReached", fn: func() *AppError { return SessionMaxLifetimeReached() }},
		{name: "SessionExtensionDisabled", fn: func() *AppError { return SessionExtensionDisabled() }},
		{name: "RefreshTokenRotationFailed", fn: func() *AppError { return RefreshTokenRotationFailed(boom) }},
		{name: "InvalidRefreshTokenProvided", fn: func() *AppError { return InvalidRefreshTokenProvided() }},
		{name: "SessionSecurityCheckFailed", fn: func() *AppError { return SessionSecurityCheckFailed(boom) }},
		{name: "SessionCreationFailed", fn: func() *AppError { return SessionCreationFailed(boom) }},
		{name: "AccessTokenGenerationFailed", fn: func() *AppError { return AccessTokenGenerationFailed(boom) }},
		{name: "PasswordUpdateFailed", fn: func() *AppError { return PasswordUpdateFailed(boom) }},
	}

	for _, tc := range constructors {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.fn()
			assertAppErrorBasics(t, err)
			assert.Equal(t, CategoryAuth, err.Category)
		})
	}
}
