package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.77

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/equaltoai/lesser/graph/model"
	"github.com/equaltoai/lesser/pkg/activitypub"
	"github.com/equaltoai/lesser/pkg/common"
	"github.com/equaltoai/lesser/pkg/moderation"
	"github.com/equaltoai/lesser/pkg/storage"
	"github.com/equaltoai/lesser/pkg/streaming"
	"go.uber.org/zap"
)

// Helper function to create string pointer
func stringPtr(s string) *string {
	return &s
}

// Helper function to create float64 pointer
func floatPtr(f float64) *float64 {
	return &f
}

// Pattern is the resolver for the pattern field.
func (r *moderationPatternResolver) Pattern(_ context.Context, obj *moderation.ModerationPattern) (string, error) {
	if obj == nil {
		return "", nil
	}

	return obj.Content, nil // Content contains the pattern
}

// Type is the resolver for the type field.
func (r *moderationPatternResolver) Type(_ context.Context, obj *moderation.ModerationPattern) (model.PatternType, error) {
	if obj == nil {
		return model.PatternTypeRegex, nil // Default to regex
	}

	// Convert string type to PatternType enum
	switch strings.ToLower(obj.Type) {
	case "keyword":
		return model.PatternTypeKeyword, nil
	case "ml_model":
		return model.PatternTypeMlPattern, nil
	case "regex":
		fallthrough
	default:
		return model.PatternTypeRegex, nil
	}
}

// Severity is the resolver for the severity field.
func (r *moderationPatternResolver) Severity(_ context.Context, obj *moderation.ModerationPattern) (model.ModerationSeverity, error) {
	if obj == nil {
		return model.ModerationSeverityLow, nil // Default to low
	}

	// Convert string severity to ModerationSeverity enum
	switch strings.ToLower(obj.Severity) {
	case "critical":
		return model.ModerationSeverityCritical, nil
	case "high":
		return model.ModerationSeverityHigh, nil
	case "medium":
		return model.ModerationSeverityMedium, nil
	case "low":
		fallthrough
	default:
		return model.ModerationSeverityLow, nil
	}
}

// FalsePositiveRate is the resolver for the falsePositiveRate field.
func (r *moderationPatternResolver) FalsePositiveRate(_ context.Context, obj *moderation.ModerationPattern) (float64, error) {
	if obj == nil {
		return 0.0, nil
	}

	// Calculate false positive rate from available data
	if obj.MatchCount > 0 && obj.FalsePositiveCount >= 0 {
		return float64(obj.FalsePositiveCount) / float64(obj.MatchCount), nil
	}

	// Use effectiveness to approximate false positive rate
	if obj.Effectiveness > 0 {
		return 1.0 - obj.Effectiveness, nil
	}

	return 0.05, nil // Default 5% false positive rate
}

// CreatedAt is the resolver for the createdAt field.
func (r *moderationPatternResolver) CreatedAt(_ context.Context, obj *moderation.ModerationPattern) (*model.Time, error) {
	if obj == nil {
		return nil, nil
	}

	if obj.CreatedAt.IsZero() {
		return nil, nil
	}

	gqlTime := model.Time(obj.CreatedAt)
	return &gqlTime, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *moderationPatternResolver) UpdatedAt(_ context.Context, obj *moderation.ModerationPattern) (*model.Time, error) {
	if obj == nil {
		return nil, nil
	}

	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}

	gqlTime := model.Time(obj.UpdatedAt)
	return &gqlTime, nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *moderationPatternResolver) CreatedBy(ctx context.Context, obj *moderation.ModerationPattern) (*activitypub.Actor, error) {
	if obj == nil || obj.CreatedBy == "" {
		return nil, nil
	}

	// Use DataLoader to fetch the creator actor
	actor, err := LoadActor(ctx, obj.CreatedBy)
	if err != nil {
		r.Logger.Warn("Failed to load pattern creator actor",
			zap.String("actorID", obj.CreatedBy),
			zap.Error(err))
		return nil, nil // Return nil instead of error for optional field
	}

	return actor, nil
}

// RequestStreamingURL generates a streaming URL for media
func (r *mutationResolver) RequestStreamingURL(_ context.Context, mediaID string, quality *model.StreamQuality) (*model.MediaStream, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Default to auto quality
	selectedQuality := model.StreamQualityAuto
	if quality != nil {
		selectedQuality = *quality
	}

	// Generate streaming URL
	baseURL := fmt.Sprintf("https://cdn.lesser.app/media/%s", mediaID)

	stream := &model.MediaStream{
		ID:              mediaID,
		URL:             fmt.Sprintf("%s/stream-%s", baseURL, selectedQuality),
		HlsPlaylistURL:  stringPtr(fmt.Sprintf("%s/playlist-%s.m3u8", baseURL, selectedQuality)),
		DashManifestURL: stringPtr(fmt.Sprintf("%s/manifest-%s.mpd", baseURL, selectedQuality)),
		ThumbnailURL:    baseURL + "/thumb.jpg",
		Duration:        120,
		ExpiresAt:       model.Time(time.Now().Add(6 * time.Hour)),
		Bitrates:        []*model.Bitrate{}, // Would be populated based on quality
	}

	// Add appropriate bitrate
	switch selectedQuality {
	case model.StreamQualityLow:
		stream.Bitrates = append(stream.Bitrates, &model.Bitrate{
			Quality:       model.StreamQualityLow,
			BitsPerSecond: 500000,
			Width:         854,
			Height:        480,
			Codec:         "h264",
		})
	case model.StreamQualityMedium:
		stream.Bitrates = append(stream.Bitrates, &model.Bitrate{
			Quality:       model.StreamQualityMedium,
			BitsPerSecond: 1500000,
			Width:         1280,
			Height:        720,
			Codec:         "h264",
		})
	case model.StreamQualityHigh:
		stream.Bitrates = append(stream.Bitrates, &model.Bitrate{
			Quality:       model.StreamQualityHigh,
			BitsPerSecond: 4000000,
			Width:         1920,
			Height:        1080,
			Codec:         "h264",
		})
	default: // Auto includes all
		stream.Bitrates = []*model.Bitrate{
			{Quality: model.StreamQualityLow, BitsPerSecond: 500000, Width: 854, Height: 480, Codec: "h264"},
			{Quality: model.StreamQualityMedium, BitsPerSecond: 1500000, Width: 1280, Height: 720, Codec: "h264"},
			{Quality: model.StreamQualityHigh, BitsPerSecond: 4000000, Width: 1920, Height: 1080, Codec: "h264"},
		}
	}

	r.Logger.Info("Generated streaming URL",
		zap.String("mediaID", mediaID),
		zap.String("quality", string(selectedQuality)))

	return stream, nil
}

// PreloadMedia prepares multiple media items for streaming
func (r *mutationResolver) PreloadMedia(ctx context.Context, mediaIDs []string) ([]*model.MediaStream, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(len(mediaIDs))

	streams := make([]*model.MediaStream, 0, len(mediaIDs))

	for _, mediaID := range mediaIDs {
		stream, err := r.RequestStreamingURL(ctx, mediaID, nil)
		if err != nil {
			r.Logger.Warn("Failed to preload media",
				zap.String("mediaID", mediaID),
				zap.Error(err))
			continue
		}
		streams = append(streams, stream)
	}

	return streams, nil
}

// CreateModerationPattern creates a new moderation pattern
func (r *mutationResolver) CreateModerationPattern(ctx context.Context, input model.ModerationPatternInput) (*moderation.ModerationPattern, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Create the pattern using the correct struct from pkg/moderation
	pattern := &moderation.ModerationPattern{
		ID:                 fmt.Sprintf("pattern-%s", generateID()),
		Content:            input.Pattern, // Note: Content field, not Pattern
		Type:               string(input.Type),
		Severity:           string(input.Severity),
		MatchCount:         0,
		FalsePositiveCount: 0,
		CreatedAt:          time.Now(),
		UpdatedAt:          time.Now(),
		Active:             true,
	}

	if input.Active != nil {
		pattern.Active = *input.Active
	}

	// Create the pattern in storage
	storagePattern := &storage.ModerationPattern{
		ID:        pattern.ID,
		Pattern:   pattern.Content,
		Content:   pattern.Content,
		Type:      pattern.Type,
		Severity:  pattern.Severity,
		Active:    pattern.Active,
		Enabled:   pattern.Active,
		CreatedAt: pattern.CreatedAt,
		UpdatedAt: pattern.UpdatedAt,
	}

	err := r.Storage.Moderation().CreateModerationPattern(ctx, storagePattern)
	if err != nil {
		r.Logger.Error("Failed to create moderation pattern",
			zap.String("id", pattern.ID),
			zap.Error(err))
		return nil, fmt.Errorf("failed to create moderation pattern: %w", err)
	}

	r.Logger.Info("Created moderation pattern",
		zap.String("id", pattern.ID),
		zap.String("type", pattern.Type))

	return pattern, nil
}

// UpdateModerationPattern updates an existing moderation pattern
func (r *mutationResolver) UpdateModerationPattern(ctx context.Context, id string, input model.ModerationPatternInput) (*moderation.ModerationPattern, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Get moderation repository
	moderationRepo := r.Storage.Moderation()

	// Try to get the existing pattern from repository
	existingPattern, err := moderationRepo.GetModerationPattern(ctx, id)
	if err != nil {
		r.Logger.Error("Failed to get moderation pattern for update",
			zap.String("id", id),
			zap.Error(err))
		return nil, fmt.Errorf("pattern not found: %w", err)
	}

	// Update the pattern with new values
	existingPattern.Pattern = input.Pattern
	existingPattern.Type = string(input.Type)
	existingPattern.Severity = string(input.Severity)
	existingPattern.UpdatedAt = time.Now()
	if input.Active != nil {
		existingPattern.Active = *input.Active
	}

	// Save the updated pattern
	err = moderationRepo.UpdateModerationPattern(ctx, existingPattern)
	if err != nil {
		r.Logger.Error("Failed to update moderation pattern",
			zap.String("id", id),
			zap.Error(err))
		return nil, fmt.Errorf("failed to update moderation pattern: %w", err)
	}

	// Convert to moderation.ModerationPattern for return
	pattern := &moderation.ModerationPattern{
		ID:                 existingPattern.ID,
		Content:            existingPattern.Content,
		Type:               existingPattern.Type,
		Severity:           existingPattern.Severity,
		MatchCount:         int64(existingPattern.MatchCount),
		FalsePositiveCount: int64(existingPattern.FalsePositiveCount),
		CreatedAt:          existingPattern.CreatedAt,
		UpdatedAt:          existingPattern.UpdatedAt,
		Active:             existingPattern.Active,
	}

	return pattern, nil
}

// DeleteModerationPattern deletes a moderation pattern
func (r *mutationResolver) DeleteModerationPattern(ctx context.Context, id string) (bool, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Delete the pattern
	err := r.Storage.Moderation().DeleteModerationPattern(ctx, id)
	if err != nil {
		r.Logger.Error("Failed to delete moderation pattern",
			zap.String("id", id),
			zap.Error(err))
		return false, fmt.Errorf("failed to delete moderation pattern: %w", err)
	}

	r.Logger.Info("Deleted moderation pattern", zap.String("id", id))

	return true, nil
}

// TrainModerationModel trains the ML moderation model with samples
func (r *mutationResolver) TrainModerationModel(_ context.Context, samples []*model.ModerationSample) (*model.TrainingResult, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(len(samples))

	// Simulate training (in production, would send to ML service)
	result := &model.TrainingResult{
		Success:      true,
		ModelVersion: "2.1.0",
		Accuracy:     0.94,
		Precision:    0.92,
		Recall:       0.96,
		SamplesUsed:  len(samples),
		TrainingTime: 145, // seconds
		Improvements: []string{
			"Improved hate speech detection by 8%",
			"Reduced false positives for sarcasm by 12%",
			"Added support for 3 new languages",
		},
	}

	r.Logger.Info("Trained moderation model",
		zap.Int("samples", len(samples)),
		zap.Float64("accuracy", result.Accuracy))

	return result, nil
}

// SetFederationLimit sets limits for a specific domain
func (r *mutationResolver) SetFederationLimit(_ context.Context, domain string, limit model.FederationLimitInput) (*model.FederationLimit, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Create or update limit
	federationLimit := &model.FederationLimit{
		Domain:            domain,
		IngressLimitMb:    100, // Default
		EgressLimitMb:     50,  // Default
		RequestsPerMinute: 60,  // Default
		Active:            true,
		CreatedAt:         model.Time(time.Now()),
		UpdatedAt:         model.Time(time.Now()),
	}

	// Apply input values
	if limit.IngressLimitMb != nil {
		federationLimit.IngressLimitMb = *limit.IngressLimitMb
	}
	if limit.EgressLimitMb != nil {
		federationLimit.EgressLimitMb = *limit.EgressLimitMb
	}
	if limit.RequestsPerMinute != nil {
		federationLimit.RequestsPerMinute = *limit.RequestsPerMinute
	}
	if limit.MonthlyBudgetUsd != nil {
		federationLimit.MonthlyBudgetUsd = limit.MonthlyBudgetUsd
	}

	r.Logger.Info("Set federation limit",
		zap.String("domain", domain),
		zap.Int("ingressMB", federationLimit.IngressLimitMb))

	return federationLimit, nil
}

// PauseFederation pauses federation with a domain
func (r *mutationResolver) PauseFederation(_ context.Context, domain string, reason string, until *model.Time) (*model.FederationManagementStatus, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	status := &model.FederationManagementStatus{
		Domain:      domain,
		Status:      model.FederationStatePaused,
		Reason:      &reason,
		PausedUntil: until,
		Metrics: &model.FederationMetrics{
			CurrentMonthCostUsd:     0,
			CurrentMonthRequests:    0,
			CurrentMonthBandwidthMb: 0,
			AverageResponseTime:     0,
			ErrorRate:               0,
		},
	}

	r.Logger.Info("Paused federation",
		zap.String("domain", domain),
		zap.String("reason", reason))

	return status, nil
}

// ResumeFederation resumes federation with a domain
func (r *mutationResolver) ResumeFederation(_ context.Context, domain string) (*model.FederationManagementStatus, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	status := &model.FederationManagementStatus{
		Domain: domain,
		Status: model.FederationStateActive,
		Metrics: &model.FederationMetrics{
			CurrentMonthCostUsd:     25.50,
			CurrentMonthRequests:    50000,
			CurrentMonthBandwidthMb: 1024,
			AverageResponseTime:     1.5,
			ErrorRate:               0.02,
		},
	}

	r.Logger.Info("Resumed federation", zap.String("domain", domain))

	return status, nil
}

// SetInstanceBudget sets the monthly budget for an instance
func (r *mutationResolver) SetInstanceBudget(_ context.Context, domain string, monthlyUsd float64, autoLimit *bool) (*model.InstanceBudget, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Default auto-limit to true
	autoLimitEnabled := true
	if autoLimit != nil {
		autoLimitEnabled = *autoLimit
	}

	budget := &model.InstanceBudget{
		Domain:             domain,
		MonthlyBudgetUsd:   monthlyUsd,
		CurrentSpendUsd:    0, // Would be calculated from actual usage
		RemainingBudgetUsd: monthlyUsd,
		ProjectedOverspend: nil,
		AlertThreshold:     0.8,
		AutoLimit:          autoLimitEnabled,
		Period:             time.Now().Format(common.MonthFormat),
	}

	r.Logger.Info("Set instance budget",
		zap.String("domain", domain),
		zap.Float64("monthlyUSD", monthlyUsd),
		zap.Bool("autoLimit", autoLimitEnabled))

	return budget, nil
}

// OptimizeFederationCosts runs cost optimization analysis
func (r *mutationResolver) OptimizeFederationCosts(_ context.Context, threshold float64) (*model.CostOptimizationResult, error) {
	// Track the mutation
	_ = r.CostTracker.TrackDynamoWrite(1)

	// Simulate optimization analysis
	result := &model.CostOptimizationResult{
		Optimized:       5,
		SavedMonthlyUsd: 125.50,
		Actions: []*model.OptimizationAction{
			{
				Domain:     "high-traffic.social",
				Action:     "Enable request batching",
				SavingsUsd: 45.00,
				Impact:     "Reduces API calls by 30%",
			},
			{
				Domain:     "media-heavy.instance",
				Action:     "Compress media before storage",
				SavingsUsd: 35.50,
				Impact:     "Reduces storage costs by 25%",
			},
			{
				Domain:     "chatty.social",
				Action:     "Implement caching strategy",
				SavingsUsd: 25.00,
				Impact:     "Reduces repeated fetches by 40%",
			},
			{
				Domain:     "archive.instance",
				Action:     "Move old content to cold storage",
				SavingsUsd: 20.00,
				Impact:     "Reduces storage costs by 60%",
			},
		},
	}

	r.Logger.Info("Ran cost optimization",
		zap.Float64("threshold", threshold),
		zap.Float64("savedUSD", result.SavedMonthlyUsd))

	return result, nil
}

// FederationCosts returns federation cost data with pagination
func (r *queryResolver) FederationCosts(ctx context.Context, first *int, after *string, _ *model.CostOrderBy) (*model.FederationCostConnection, error) {
	// Track the query cost
	_ = r.CostTracker.TrackDynamoRead(1)

	// Default pagination
	limit := 20
	if first != nil && *first > 0 && *first <= 100 {
		limit = *first
	}

	// Get cursor for pagination
	cursor := ""
	if after != nil {
		cursor = *after
	}

	// Fetch real federation costs from storage
	endTime := time.Now()
	startTime := endTime.AddDate(0, -1, 0) // Last month

	costs, nextCursor, err := r.Storage.Federation().GetFederationCosts(ctx, startTime, endTime, limit, cursor)
	if err != nil {
		r.Logger.Error("Failed to get federation costs", zap.Error(err))
		// Return empty result instead of error for better UX
		return &model.FederationCostConnection{
			Edges: []*model.FederationCostEdge{},
			PageInfo: &model.PageInfo{
				HasNextPage:     false,
				HasPreviousPage: false,
			},
			TotalCount: 0,
		}, nil
	}

	// Convert to GraphQL model
	edges := make([]*model.FederationCostEdge, 0, len(costs))

	for i, cost := range costs {
		// Calculate health score based on error rate
		healthScore := (1.0 - cost.ErrorRate) * 100

		// Generate recommendation based on metrics
		var recommendation string
		if cost.ErrorRate > 0.05 {
			recommendation = "Consider rate limiting due to high error rate"
		} else if healthScore > 95 {
			recommendation = "Healthy federation, no action needed"
		} else {
			recommendation = "Monitor federation health"
		}

		federationCost := &model.FederationCost{
			Domain:         cost.Domain,
			IngressBytes:   int(cost.IngressBytes),
			EgressBytes:    int(cost.EgressBytes),
			RequestCount:   int(cost.RequestCount),
			ErrorRate:      cost.ErrorRate,
			MonthlyCostUsd: cost.EstimatedCostUSD,
			HealthScore:    healthScore,
			Recommendation: &recommendation,
			LastUpdated:    model.Time(cost.LastUpdated),
		}

		// Add cost breakdown
		federationCost.Breakdown = &model.CostBreakdown{
			Period:           model.PeriodMonth,
			TotalCost:        cost.EstimatedCostUSD,
			DynamoDBCost:     cost.EstimatedCostUSD * 0.3,
			S3StorageCost:    cost.EstimatedCostUSD * 0.2,
			LambdaCost:       cost.EstimatedCostUSD * 0.4,
			DataTransferCost: cost.EstimatedCostUSD * 0.1,
			Breakdown: []*model.CostItem{
				{
					Operation: "Federation Ingress",
					Count:     int(cost.IngressBytes / 1000000), // Convert to MB
					Cost:      cost.EstimatedCostUSD * 0.4,
				},
				{
					Operation: "Federation Egress",
					Count:     int(cost.EgressBytes / 1000000), // Convert to MB
					Cost:      cost.EstimatedCostUSD * 0.3,
				},
				{
					Operation: "Request Processing",
					Count:     int(cost.RequestCount),
					Cost:      cost.EstimatedCostUSD * 0.3,
				},
			},
		}

		edge := &model.FederationCostEdge{
			Node:   federationCost,
			Cursor: model.Cursor(fmt.Sprintf("%s#%d", cost.Domain, i)),
		}
		edges = append(edges, edge)
	}

	// Create page info
	pageInfo := &model.PageInfo{
		HasNextPage:     nextCursor != "",
		HasPreviousPage: cursor != "",
	}

	if len(edges) > 0 {
		pageInfo.StartCursor = &edges[0].Cursor
		pageInfo.EndCursor = &edges[len(edges)-1].Cursor
	}

	// Create connection
	connection := &model.FederationCostConnection{
		Edges:      edges,
		PageInfo:   pageInfo,
		TotalCount: len(edges),
	}

	r.Logger.Info("Federation costs queried",
		zap.Int("count", len(edges)),
		zap.Bool("hasNext", nextCursor != ""))

	return connection, nil
}

// InstanceHealthReport returns detailed health report for a specific instance
func (r *queryResolver) InstanceHealthReport(ctx context.Context, domain string) (*model.InstanceHealthReport, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(2) // Multiple reads for detailed report

	// Get health report from storage (last 24 hours)
	healthReport, err := r.Storage.Federation().GetInstanceHealthReport(ctx, domain, 24*time.Hour)
	if err != nil {
		r.Logger.Error("Failed to get instance health report",
			zap.String("domain", domain),
			zap.Error(err))

		// Return a default report on error
		return &model.InstanceHealthReport{
			Domain: domain,
			Status: model.InstanceHealthStatusUnknown,
			Metrics: &model.InstanceHealthMetrics{
				ResponseTime:    0,
				ErrorRate:       0,
				FederationDelay: 0,
				QueueDepth:      0,
				CostEfficiency:  0,
			},
			Issues:          []*model.HealthIssue{},
			Recommendations: []string{"Unable to retrieve health data"},
			LastChecked:     model.Time(time.Now()),
		}, nil
	}

	// Convert storage model to GraphQL model
	var status model.InstanceHealthStatus
	switch healthReport.Status {
	case HealthStatusCritical:
		status = model.InstanceHealthStatusCritical
	case HealthStatusWarning:
		status = model.InstanceHealthStatusWarning
	case HealthStatusHealthy:
		status = model.InstanceHealthStatusHealthy
	default:
		status = model.InstanceHealthStatusUnknown
	}

	// Convert issues to GraphQL model
	issues := make([]*model.HealthIssue, 0, len(healthReport.Issues))
	for _, issue := range healthReport.Issues {
		// Determine severity based on issue content
		severity := model.IssueSeverityLow
		if strings.Contains(issue, "High error rate") || strings.Contains(issue, "critical") {
			severity = model.IssueSeverityCritical
		} else if strings.Contains(issue, "Elevated") || strings.Contains(issue, "warning") {
			severity = model.IssueSeverityMedium
		}

		// Determine type from issue description
		issueType := "other"
		if strings.Contains(strings.ToLower(issue), HealthStatusError) {
			issueType = HealthStatusError
		} else if strings.Contains(strings.ToLower(issue), "performance") {
			issueType = "performance"
		} else if strings.Contains(strings.ToLower(issue), "timeout") {
			issueType = "timeout"
		}

		// Determine impact from issue description
		impact := "Minor issue, no immediate action required"
		if strings.Contains(strings.ToLower(issue), "critical") {
			impact = "Service disruption, immediate action required"
		} else if strings.Contains(strings.ToLower(issue), "error") {
			impact = "Service degradation, may affect user experience"
		} else if strings.Contains(strings.ToLower(issue), "warning") {
			impact = "Potential issue, monitoring recommended"
		}

		healthIssue := &model.HealthIssue{
			Type:        issueType,
			Severity:    severity,
			Description: issue,
			DetectedAt:  model.Time(healthReport.LastChecked),
			Impact:      impact,
		}
		issues = append(issues, healthIssue)
	}

	// Calculate cost efficiency based on error rate and response time
	costEfficiency := 1.0 - healthReport.ErrorRate
	if healthReport.ResponseTime > 1000 { // Penalize slow responses
		costEfficiency *= (1000 / healthReport.ResponseTime)
	}

	report := &model.InstanceHealthReport{
		Domain: domain,
		Status: status,
		Metrics: &model.InstanceHealthMetrics{
			ResponseTime:    healthReport.ResponseTime / 1000, // Convert ms to seconds
			ErrorRate:       healthReport.ErrorRate,
			FederationDelay: healthReport.FederationDelay,
			QueueDepth:      int(healthReport.QueueDepth),
			CostEfficiency:  costEfficiency,
		},
		Issues:          issues,
		Recommendations: healthReport.Recommendations,
		LastChecked:     model.Time(healthReport.LastChecked),
	}

	return report, nil
}

// CostProjections returns cost projections for the specified period
func (r *queryResolver) CostProjections(ctx context.Context, period model.Period) (*model.CostProjection, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	periodStr := string(period)
	r.Logger.Debug("getting cost projections from repository",
		zap.String("period", periodStr))

	// Get cost projections from the repository
	projections, err := r.Storage.Cost().GetCostProjections(ctx, periodStr)
	if err != nil {
		r.Logger.Error("failed to get cost projections",
			zap.String("period", periodStr),
			zap.Error(err))

		// Return default projections on error
		return &model.CostProjection{
			Period:          period,
			CurrentCost:     0,
			ProjectedCost:   0,
			Variance:        0,
			TopCostDrivers:  []*model.CostDriver{},
			Recommendations: []string{"Unable to generate projections"},
		}, nil
	}

	// Convert storage model to GraphQL model
	topDrivers := make([]*model.CostDriver, 0, len(projections.TopDrivers))
	for _, driver := range projections.TopDrivers {
		// Determine trend
		trend := model.TrendStable
		switch driver.Trend {
		case "increasing":
			trend = model.TrendIncreasing
		case "decreasing":
			trend = model.TrendDecreasing
		}

		costDriver := &model.CostDriver{
			Type:           driver.Type,
			Domain:         &driver.Domain,
			Cost:           driver.Cost,
			PercentOfTotal: driver.PercentOfTotal,
			Trend:          trend,
		}

		// Only set domain if it's not empty
		if driver.Domain == "" {
			costDriver.Domain = nil
		}

		topDrivers = append(topDrivers, costDriver)
	}

	projection := &model.CostProjection{
		Period:          period,
		CurrentCost:     projections.CurrentCost,
		ProjectedCost:   projections.ProjectedCost,
		Variance:        projections.Variance,
		TopCostDrivers:  topDrivers,
		Recommendations: projections.Recommendations,
	}

	return projection, nil
}

// MediaStreamURL returns a streaming URL for the specified media
func (r *queryResolver) MediaStreamURL(_ context.Context, mediaID string) (*model.MediaStream, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	// Generate streaming URLs (in production, these would come from a CDN)
	baseURL := fmt.Sprintf("https://cdn.lesser.app/media/%s", mediaID)

	stream := &model.MediaStream{
		ID:              mediaID,
		URL:             baseURL + "/original",
		HlsPlaylistURL:  stringPtr(baseURL + "/playlist.m3u8"),
		DashManifestURL: stringPtr(baseURL + "/manifest.mpd"),
		ThumbnailURL:    baseURL + "/thumb.jpg",
		Duration:        120, // 2 minutes
		ExpiresAt:       model.Time(time.Now().Add(24 * time.Hour)),
		Bitrates: []*model.Bitrate{
			{
				Quality:       model.StreamQualityLow,
				BitsPerSecond: 500000,
				Width:         854,
				Height:        480,
				Codec:         "h264",
			},
			{
				Quality:       model.StreamQualityMedium,
				BitsPerSecond: 1500000,
				Width:         1280,
				Height:        720,
				Codec:         "h264",
			},
			{
				Quality:       model.StreamQualityHigh,
				BitsPerSecond: 4000000,
				Width:         1920,
				Height:        1080,
				Codec:         "h264",
			},
		},
	}

	return stream, nil
}

// SupportedBitrates returns available bitrates for a media item
func (r *queryResolver) SupportedBitrates(_ context.Context, _ string) ([]*model.Bitrate, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	// Return standard bitrates (in production, would check actual media capabilities)
	bitrates := []*model.Bitrate{
		{
			Quality:       model.StreamQualityAuto,
			BitsPerSecond: 0, // Auto-adaptive
			Width:         0,
			Height:        0,
			Codec:         "h264",
		},
		{
			Quality:       model.StreamQualityLow,
			BitsPerSecond: 500000,
			Width:         854,
			Height:        480,
			Codec:         "h264",
		},
		{
			Quality:       model.StreamQualityMedium,
			BitsPerSecond: 1500000,
			Width:         1280,
			Height:        720,
			Codec:         "h264",
		},
		{
			Quality:       model.StreamQualityHigh,
			BitsPerSecond: 4000000,
			Width:         1920,
			Height:        1080,
			Codec:         "h264",
		},
	}

	return bitrates, nil
}

// ModerationPatterns returns moderation patterns with filtering
func (r *queryResolver) ModerationPatterns(ctx context.Context, active *bool, severity *model.ModerationSeverity, first *int, _ *string) ([]*moderation.ModerationPattern, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	// Get patterns from storage (use default parameters if not specified)
	activeFilter := true
	if active != nil {
		activeFilter = *active
	}
	severityFilter := ""
	if severity != nil {
		severityFilter = string(*severity)
	}
	limitFilter := 100
	if first != nil {
		limitFilter = *first
	}

	storagePatterns, err := r.Storage.Moderation().GetModerationPatterns(ctx, activeFilter, severityFilter, limitFilter)
	if err != nil {
		r.Logger.Error("Failed to get moderation patterns",
			zap.Error(err))
		return nil, fmt.Errorf("failed to get moderation patterns: %w", err)
	}

	// Convert to moderation.ModerationPattern
	patterns := make([]*moderation.ModerationPattern, 0, len(storagePatterns))
	for _, sp := range storagePatterns {
		pattern := &moderation.ModerationPattern{
			ID:                 sp.ID,
			Content:            sp.Content,
			Type:               sp.Type,
			Severity:           sp.Severity,
			MatchCount:         int64(sp.MatchCount),
			FalsePositiveCount: int64(sp.FalsePositiveCount),
			CreatedAt:          sp.CreatedAt,
			UpdatedAt:          sp.UpdatedAt,
			Active:             sp.Active,
		}
		patterns = append(patterns, pattern)
	}

	return patterns, nil
}

// ModerationEffectiveness returns effectiveness metrics for a pattern
func (r *queryResolver) ModerationEffectiveness(_ context.Context, patternID string, _ model.Period) (*model.ModerationEffectiveness, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(2)

	// Calculate effectiveness metrics
	truePositives := 850
	falsePositives := 23
	missedCount := 45
	matchCount := truePositives + falsePositives

	precision := float64(truePositives) / float64(truePositives+falsePositives)
	recall := float64(truePositives) / float64(truePositives+missedCount)
	f1Score := 2 * (precision * recall) / (precision + recall)

	effectiveness := &model.ModerationEffectiveness{
		PatternID:      patternID,
		MatchCount:     matchCount,
		TruePositives:  truePositives,
		FalsePositives: falsePositives,
		MissedCount:    missedCount,
		Precision:      precision,
		Recall:         recall,
		F1Score:        f1Score,
	}

	return effectiveness, nil
}

// FederationLimits returns configured federation limits
func (r *queryResolver) FederationLimits(_ context.Context, active *bool, _ *int, _ *string) ([]*model.FederationLimit, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	// Sample limits (in production, would fetch from configuration)
	limits := []*model.FederationLimit{
		{
			Domain:            "high-traffic.social",
			IngressLimitMb:    1024, // 1GB
			EgressLimitMb:     512,  // 512MB
			RequestsPerMinute: 100,
			MonthlyBudgetUsd:  floatPtr(50.0),
			Active:            true,
			CreatedAt:         model.Time(time.Now().Add(-7 * 24 * time.Hour)),
			UpdatedAt:         model.Time(time.Now()),
		},
		{
			Domain:            "problematic.instance",
			IngressLimitMb:    10,
			EgressLimitMb:     5,
			RequestsPerMinute: 10,
			MonthlyBudgetUsd:  floatPtr(5.0),
			Active:            true,
			CreatedAt:         model.Time(time.Now().Add(-1 * 24 * time.Hour)),
			UpdatedAt:         model.Time(time.Now()),
		},
	}

	// Apply active filter
	if active != nil {
		var filtered []*model.FederationLimit
		for _, limit := range limits {
			if limit.Active == *active {
				filtered = append(filtered, limit)
			}
		}
		return filtered, nil
	}

	return limits, nil
}

// InstanceBudgets returns budget information for instances
func (r *queryResolver) InstanceBudgets(_ context.Context, exceeded *bool) ([]*model.InstanceBudget, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	// Sample budgets
	budgets := []*model.InstanceBudget{
		{
			Domain:             "mastodon.social",
			MonthlyBudgetUsd:   100.0,
			CurrentSpendUsd:    85.50,
			RemainingBudgetUsd: 14.50,
			ProjectedOverspend: nil,
			AlertThreshold:     0.8,
			AutoLimit:          true,
			Period:             "2024-01",
		},
		{
			Domain:             "expensive.instance",
			MonthlyBudgetUsd:   50.0,
			CurrentSpendUsd:    52.30,
			RemainingBudgetUsd: -2.30,
			ProjectedOverspend: floatPtr(8.50),
			AlertThreshold:     0.8,
			AutoLimit:          false,
			Period:             "2024-01",
		},
	}

	// Apply exceeded filter
	if exceeded != nil && *exceeded {
		var filtered []*model.InstanceBudget
		for _, budget := range budgets {
			if budget.CurrentSpendUsd > budget.MonthlyBudgetUsd {
				filtered = append(filtered, budget)
			}
		}
		return filtered, nil
	}

	return budgets, nil
}

// FederationHealth returns health status for instances
func (r *queryResolver) FederationHealth(_ context.Context, threshold *float64) ([]*model.FederationManagementStatus, error) {
	// Track the query
	_ = r.CostTracker.TrackDynamoRead(1)

	// Default threshold
	healthThreshold := 0.8
	if threshold != nil {
		healthThreshold = *threshold
	}

	// Sample health data
	statuses := []*model.FederationManagementStatus{
		{
			Domain: "healthy.social",
			Status: model.FederationStateActive,
			Metrics: &model.FederationMetrics{
				CurrentMonthCostUsd:     45.20,
				CurrentMonthRequests:    125000,
				CurrentMonthBandwidthMb: 2048,
				AverageResponseTime:     1.2,
				ErrorRate:               0.01,
			},
		},
		{
			Domain: "struggling.instance",
			Status: model.FederationStateLimited,
			Reason: stringPtr("High error rate detected"),
			Limits: &model.FederationLimit{
				Domain:            "struggling.instance",
				RequestsPerMinute: 10,
				Active:            true,
			},
			Metrics: &model.FederationMetrics{
				CurrentMonthCostUsd:     78.50,
				CurrentMonthRequests:    89000,
				CurrentMonthBandwidthMb: 1500,
				AverageResponseTime:     8.5,
				ErrorRate:               0.15,
			},
		},
	}

	// Filter by health threshold
	var filtered []*model.FederationManagementStatus
	for _, status := range statuses {
		// Calculate health score (simple formula)
		healthScore := (1.0 - status.Metrics.ErrorRate) * (1.0 / status.Metrics.AverageResponseTime)
		if healthScore >= healthThreshold {
			filtered = append(filtered, status)
		}
	}

	return filtered, nil
}

// ModerationAlerts streams real-time moderation alerts
func (r *subscriptionResolver) ModerationAlerts(ctx context.Context, severity *model.ModerationSeverity) (<-chan *model.ModerationAlert, error) {
	// Initialize subscription manager if not already done
	if r.SubscriptionManager == nil {
		_ = os.Getenv("SUBSCRIPTIONS_TABLE") // Environment variable read but table name not used in current implementation
		r.SubscriptionManager = NewSubscriptionManager(r.Logger)
	}

	// Track read for subscription
	_ = r.CostTracker.TrackDynamoRead(1)

	// Create channel for alerts
	alerts := make(chan *model.ModerationAlert, 10)

	// Subscribe to moderation events via event bus
	go func() {
		defer close(alerts)

		// Create event filter for moderation events
		filter := &streaming.EventFilter{
			Types: []streaming.EventType{
				streaming.EventTypeModeration,
				streaming.EventTypeModerationFlag,
				streaming.EventTypeModerationReview,
			},
			MinPriority: streaming.PriorityNormal,
		}

		// Try to get the global event bus
		eventBus := getGlobalStreamRouterEventBus()
		if eventBus == nil {
			r.Logger.Warn("Event bus not available for ModerationAlerts subscription")
			return
		}

		// Create a subscription to the event bus
		subscriptionID := fmt.Sprintf("moderation-alerts-%s", generateID())
		subscriber, err := eventBus.Subscribe(subscriptionID, filter, 100)
		if err != nil {
			r.Logger.Error("Failed to subscribe to moderation events", zap.Error(err))
			return
		}
		defer func() { _ = eventBus.Unsubscribe(subscriber.ID) }()

		for {
			select {
			case <-ctx.Done():
				return
			case event := <-subscriber.Channel:
				if event == nil {
					continue
				}

				// Convert streaming event to moderation alert
				alert := convertModerationEventToAlert(event)
				if alert == nil {
					continue
				}

				// Apply severity filter
				if severity != nil && alert.Severity != *severity {
					continue
				}

				select {
				case alerts <- alert:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return alerts, nil
}

// CostAlerts streams cost threshold alerts
func (r *subscriptionResolver) CostAlerts(ctx context.Context, thresholdUsd float64) (<-chan *model.CostAlert, error) {
	// Initialize subscription manager if not already done
	if r.SubscriptionManager == nil {
		_ = os.Getenv("SUBSCRIPTIONS_TABLE") // Environment variable read but table name not used in current implementation
		r.SubscriptionManager = NewSubscriptionManager(r.Logger)
	}

	// Track read for subscription
	_ = r.CostTracker.TrackDynamoRead(1)

	// Create channel for alerts
	alerts := make(chan *model.CostAlert, 10)

	// Subscribe to cost alert events via event bus
	go func() {
		defer close(alerts)

		// Create event filter for cost alert events
		filter := &streaming.EventFilter{
			Types: []streaming.EventType{
				streaming.EventTypeCostAlert,
				streaming.EventTypeCostUpdate,
			},
			MinPriority: streaming.PriorityNormal,
		}

		// Try to get the global event bus
		eventBus := getGlobalStreamRouterEventBus()
		if eventBus == nil {
			r.Logger.Warn("Event bus not available for CostAlerts subscription")
			return
		}

		// Create a subscription to the event bus
		subscriptionID := fmt.Sprintf("cost-alerts-%s", generateID())
		subscriber, err := eventBus.Subscribe(subscriptionID, filter, 100)
		if err != nil {
			r.Logger.Error("Failed to subscribe to cost alert events", zap.Error(err))
			return
		}
		defer func() { _ = eventBus.Unsubscribe(subscriber.ID) }()

		for {
			select {
			case <-ctx.Done():
				return
			case event := <-subscriber.Channel:
				if event == nil {
					continue
				}

				// Convert streaming event to cost alert
				alert := convertCostEventToAlert(event, thresholdUsd)
				if alert == nil {
					continue
				}

				select {
				case alerts <- alert:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return alerts, nil
}

// BudgetAlerts streams budget alerts for instances
func (r *subscriptionResolver) BudgetAlerts(ctx context.Context, domain *string) (<-chan *model.BudgetAlert, error) {
	// Initialize subscription manager if not already done
	if r.SubscriptionManager == nil {
		_ = os.Getenv("SUBSCRIPTIONS_TABLE") // Environment variable read but table name not used in current implementation
		r.SubscriptionManager = NewSubscriptionManager(r.Logger)
	}

	// Track read for subscription
	_ = r.CostTracker.TrackDynamoRead(1)

	// Create channel for alerts
	alerts := make(chan *model.BudgetAlert, 10)

	// Subscribe to budget/cost events via event bus
	go func() {
		defer close(alerts)

		// Create event filter for budget-related cost events
		filter := &streaming.EventFilter{
			Types: []streaming.EventType{
				streaming.EventTypeCostAlert,
				streaming.EventTypeCostUpdate,
			},
			MinPriority: streaming.PriorityNormal,
		}

		// Add domain filter if specified
		if domain != nil {
			filter.Metadata = map[string]string{
				"domain": *domain,
			}
		}

		// Try to get the global event bus
		eventBus := getGlobalStreamRouterEventBus()
		if eventBus == nil {
			r.Logger.Warn("Event bus not available for BudgetAlerts subscription")
			return
		}

		// Create a subscription to the event bus
		subscriptionID := fmt.Sprintf("budget-alerts-%s", generateID())
		subscriber, err := eventBus.Subscribe(subscriptionID, filter, 100)
		if err != nil {
			r.Logger.Error("Failed to subscribe to budget alert events", zap.Error(err))
			return
		}
		defer func() { _ = eventBus.Unsubscribe(subscriber.ID) }()

		for {
			select {
			case <-ctx.Done():
				return
			case event := <-subscriber.Channel:
				if event == nil {
					continue
				}

				// Convert streaming event to budget alert
				alert := convertCostEventToBudgetAlert(event)
				if alert == nil {
					continue
				}

				select {
				case alerts <- alert:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return alerts, nil
}

// FederationHealthUpdates streams federation health status changes
func (r *subscriptionResolver) FederationHealthUpdates(ctx context.Context, domain *string) (<-chan *model.FederationHealthUpdate, error) {
	// Initialize subscription manager if not already done
	if r.SubscriptionManager == nil {
		_ = os.Getenv("SUBSCRIPTIONS_TABLE") // Environment variable read but table name not used in current implementation
		r.SubscriptionManager = NewSubscriptionManager(r.Logger)
	}

	// Track read for subscription
	_ = r.CostTracker.TrackDynamoRead(1)

	// Create channel for updates
	updates := make(chan *model.FederationHealthUpdate, 10)

	// Subscribe to health check events via event bus
	go func() {
		defer close(updates)

		// Create event filter for health check events
		filter := &streaming.EventFilter{
			Types: []streaming.EventType{
				streaming.EventTypeHealthCheck,
				streaming.EventTypeSystemAlert,
			},
			MinPriority: streaming.PriorityNormal,
		}

		// Add domain filter if specified
		if domain != nil {
			filter.Metadata = map[string]string{
				"domain": *domain,
			}
		}

		// Try to get the global event bus
		eventBus := getGlobalStreamRouterEventBus()
		if eventBus == nil {
			r.Logger.Warn("Event bus not available for FederationHealthUpdates subscription")
			return
		}

		// Create a subscription to the event bus
		subscriptionID := fmt.Sprintf("federation-health-%s", generateID())
		subscriber, err := eventBus.Subscribe(subscriptionID, filter, 100)
		if err != nil {
			r.Logger.Error("Failed to subscribe to health check events", zap.Error(err))
			return
		}
		defer func() { _ = eventBus.Unsubscribe(subscriber.ID) }()

		for {
			select {
			case <-ctx.Done():
				return
			case event := <-subscriber.Channel:
				if event == nil {
					continue
				}

				// Convert streaming event to federation health update
				update := convertHealthEventToFederationUpdate(event)
				if update == nil {
					continue
				}

				select {
				case updates <- update:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}

// ModerationPattern returns ModerationPatternResolver implementation.
func (r *Resolver) ModerationPattern() ModerationPatternResolver {
	return &moderationPatternResolver{r}
}

type moderationPatternResolver struct{ *Resolver }

// Helper function to convert moderation event to alert
func convertModerationEventToAlert(event *streaming.InternalEvent) *model.ModerationAlert {
	if event == nil {
		return nil
	}

	// Extract moderation data from event
	var alert model.ModerationAlert
	alert.ID = event.ID
	alert.Timestamp = model.Time(event.Timestamp)
	alert.Handled = false
	alert.Confidence = 0.8 // Default confidence

	// Set severity based on event action
	switch event.Action {
	case streaming.ActionFlag:
		alert.Severity = model.ModerationSeverityHigh
		alert.SuggestedAction = model.ModerationActionRemove
	case streaming.ActionReview:
		alert.Severity = model.ModerationSeverityMedium
		alert.SuggestedAction = model.ModerationActionReview
	case streaming.ActionApprove:
		alert.Severity = model.ModerationSeverityLow
		alert.SuggestedAction = model.ModerationActionNone
	default:
		alert.Severity = model.ModerationSeverityLow
		alert.SuggestedAction = model.ModerationActionNone
	}

	// Extract matched text from metadata
	if event.Metadata != nil {
		if matchedText, ok := event.Metadata["matched_text"]; ok {
			alert.MatchedText = matchedText
		} else {
			alert.MatchedText = "Content flagged for review"
		}

		// Extract confidence if available
		if confidenceStr, ok := event.Metadata["confidence"]; ok {
			alert.Confidence = parseFloatOrZero(confidenceStr)
		}
	} else {
		alert.MatchedText = "Content flagged for review"
	}

	return &alert
}

// convertCostEventToAlert converts a cost event to a cost alert
func convertCostEventToAlert(event *streaming.InternalEvent, thresholdUSD float64) *model.CostAlert {
	if event == nil || event.Type != streaming.EventTypeCostAlert {
		return nil
	}

	alert := &model.CostAlert{
		ID:        event.ID,
		Timestamp: model.Time(event.Timestamp),
		Type:      "threshold_exceeded",
		Threshold: thresholdUSD,
		Message:   fmt.Sprintf("Cost threshold exceeded: %.2f USD", thresholdUSD),
	}

	// Extract cost details from metadata
	if event.Metadata != nil {
		if domain, ok := event.Metadata["domain"]; ok {
			alert.Domain = &domain
		}
		if costStr, ok := event.Metadata["cost_usd"]; ok {
			alert.Amount = parseFloatOrZero(costStr)
		} else {
			alert.Amount = thresholdUSD // Use threshold as amount if not specified
		}
	} else {
		alert.Amount = thresholdUSD
	}

	return alert
}

// convertCostEventToBudgetAlert converts a cost event to a budget alert
func convertCostEventToBudgetAlert(event *streaming.InternalEvent) *model.BudgetAlert {
	if event == nil {
		return nil
	}

	alert := &model.BudgetAlert{
		ID:         event.ID,
		Timestamp:  model.Time(event.Timestamp),
		Domain:     "localhost", // Default domain
		AlertLevel: model.AlertLevelWarning,
	}

	// Extract budget details from metadata
	if event.Metadata != nil {
		if domain, ok := event.Metadata["domain"]; ok {
			alert.Domain = domain
		}
		if budgetStr, ok := event.Metadata["budget_usd"]; ok {
			alert.BudgetUsd = parseFloatOrZero(budgetStr)
		}
		if spentStr, ok := event.Metadata["spent_usd"]; ok {
			alert.SpentUsd = parseFloatOrZero(spentStr)
		}

		// Calculate percentage
		if alert.BudgetUsd > 0 {
			alert.PercentUsed = (alert.SpentUsd / alert.BudgetUsd) * 100
		}

		// Set alert level based on percentage
		if alert.PercentUsed >= 90 {
			alert.AlertLevel = model.AlertLevelCritical
		} else if alert.PercentUsed >= 75 {
			alert.AlertLevel = model.AlertLevelWarning
		} else {
			alert.AlertLevel = model.AlertLevelInfo
		}

		// Check for projected overspend
		if projectedStr, ok := event.Metadata["projected_overspend"]; ok {
			overspend := parseFloatOrZero(projectedStr)
			alert.ProjectedOverspend = &overspend
		}
	}

	return alert
}

// convertHealthEventToFederationUpdate converts a health event to federation update
func convertHealthEventToFederationUpdate(event *streaming.InternalEvent) *model.FederationHealthUpdate {
	if event == nil {
		return nil
	}

	update := &model.FederationHealthUpdate{
		Domain:         "unknown",
		Timestamp:      model.Time(event.Timestamp),
		PreviousStatus: model.InstanceHealthStatusUnknown,
		CurrentStatus:  model.InstanceHealthStatusUnknown,
		Issues:         []*model.HealthIssue{},
	}

	// Extract health details from metadata
	if event.Metadata != nil {
		if domain, ok := event.Metadata["domain"]; ok {
			update.Domain = domain
		}

		// Parse previous and current status
		if prevStatus, ok := event.Metadata["previous_status"]; ok {
			update.PreviousStatus = parseHealthStatus(prevStatus)
		}
		if currStatus, ok := event.Metadata["current_status"]; ok {
			update.CurrentStatus = parseHealthStatus(currStatus)
		}

		// Extract health issues if any
		if issueType, ok := event.Metadata["issue_type"]; ok {
			issue := &model.HealthIssue{
				Type:        issueType,
				Description: event.Metadata["issue_description"],
				Severity:    model.IssueSeverityMedium,
			}

			// Parse severity if available
			if sev, ok := event.Metadata["issue_severity"]; ok {
				switch sev {
				case "high":
					issue.Severity = model.IssueSeverityHigh
				case "low":
					issue.Severity = model.IssueSeverityLow
				default:
					issue.Severity = model.IssueSeverityMedium
				}
			}

			update.Issues = append(update.Issues, issue)
		}
	}

	return update
}

// parseHealthStatus converts a string to InstanceHealthStatus
func parseHealthStatus(status string) model.InstanceHealthStatus {
	switch status {
	case HealthStatusHealthy:
		return model.InstanceHealthStatusHealthy
	case "degraded", HealthStatusWarning:
		return model.InstanceHealthStatusWarning
	case HealthStatusCritical:
		return model.InstanceHealthStatusCritical
	case "offline":
		return model.InstanceHealthStatusOffline
	default:
		return model.InstanceHealthStatusUnknown
	}
}

// parseFloatOrZero parses a string to float64, returns 0 on error
func parseFloatOrZero(s string) float64 {
	var f float64
	_, _ = fmt.Sscanf(s, "%f", &f)
	return f
}
