package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"
	"time"

	"github.com/aron23/lesser/graph/model"
	"github.com/aron23/lesser/pkg/activitypub"
	"github.com/aron23/lesser/pkg/moderation"
	"github.com/aron23/lesser/pkg/trust"
	"go.uber.org/zap"
)

// Type is the resolver for the type field.
func (r *activityResolver) Type(ctx context.Context, obj *activitypub.Activity) (model.ActivityType, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Actor is the resolver for the actor field.
func (r *activityResolver) Actor(ctx context.Context, obj *activitypub.Activity) (*activitypub.Actor, error) {
	panic(fmt.Errorf("not implemented: Actor - actor"))
}

// Object is the resolver for the object field.
func (r *activityResolver) Object(ctx context.Context, obj *activitypub.Activity) (*model.Object, error) {
	panic(fmt.Errorf("not implemented: Object - object"))
}

// Target is the resolver for the target field.
func (r *activityResolver) Target(ctx context.Context, obj *activitypub.Activity) (*model.Object, error) {
	panic(fmt.Errorf("not implemented: Target - target"))
}

// Published is the resolver for the published field.
func (r *activityResolver) Published(ctx context.Context, obj *activitypub.Activity) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: Published - published"))
}

// Cost is the resolver for the cost field.
func (r *activityResolver) Cost(ctx context.Context, obj *activitypub.Activity) (int, error) {
	panic(fmt.Errorf("not implemented: Cost - cost"))
}

// Username is the resolver for the username field.
func (r *actorResolver) Username(ctx context.Context, obj *activitypub.Actor) (string, error) {
	panic(fmt.Errorf("not implemented: Username - username"))
}

// Domain is the resolver for the domain field.
func (r *actorResolver) Domain(ctx context.Context, obj *activitypub.Actor) (*string, error) {
	panic(fmt.Errorf("not implemented: Domain - domain"))
}

// DisplayName is the resolver for the displayName field.
func (r *actorResolver) DisplayName(ctx context.Context, obj *activitypub.Actor) (*string, error) {
	panic(fmt.Errorf("not implemented: DisplayName - displayName"))
}

// Avatar is the resolver for the avatar field.
func (r *actorResolver) Avatar(ctx context.Context, obj *activitypub.Actor) (*string, error) {
	panic(fmt.Errorf("not implemented: Avatar - avatar"))
}

// Header is the resolver for the header field.
func (r *actorResolver) Header(ctx context.Context, obj *activitypub.Actor) (*string, error) {
	panic(fmt.Errorf("not implemented: Header - header"))
}

// Followers is the resolver for the followers field.
func (r *actorResolver) Followers(ctx context.Context, obj *activitypub.Actor) (int, error) {
	panic(fmt.Errorf("not implemented: Followers - followers"))
}

// Following is the resolver for the following field.
func (r *actorResolver) Following(ctx context.Context, obj *activitypub.Actor) (int, error) {
	panic(fmt.Errorf("not implemented: Following - following"))
}

// StatusesCount is the resolver for the statusesCount field.
func (r *actorResolver) StatusesCount(ctx context.Context, obj *activitypub.Actor) (int, error) {
	panic(fmt.Errorf("not implemented: StatusesCount - statusesCount"))
}

// Bot is the resolver for the bot field.
func (r *actorResolver) Bot(ctx context.Context, obj *activitypub.Actor) (bool, error) {
	panic(fmt.Errorf("not implemented: Bot - bot"))
}

// Locked is the resolver for the locked field.
func (r *actorResolver) Locked(ctx context.Context, obj *activitypub.Actor) (bool, error) {
	panic(fmt.Errorf("not implemented: Locked - locked"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *actorResolver) CreatedAt(ctx context.Context, obj *activitypub.Actor) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *actorResolver) UpdatedAt(ctx context.Context, obj *activitypub.Actor) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Fields is the resolver for the fields field.
func (r *actorResolver) Fields(ctx context.Context, obj *activitypub.Actor) ([]*model.Field, error) {
	panic(fmt.Errorf("not implemented: Fields - fields"))
}

// TrustScore is the resolver for the trustScore field.
func (r *actorResolver) TrustScore(ctx context.Context, obj *activitypub.Actor) (float64, error) {
	panic(fmt.Errorf("not implemented: TrustScore - trustScore"))
}

// ReputationSignature is the resolver for the reputationSignature field.
func (r *actorResolver) ReputationSignature(ctx context.Context, obj *activitypub.Actor) (*string, error) {
	panic(fmt.Errorf("not implemented: ReputationSignature - reputationSignature"))
}

// ID is the resolver for the id field.
func (r *attachmentResolver) ID(ctx context.Context, obj *activitypub.Attachment) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Preview is the resolver for the preview field.
func (r *attachmentResolver) Preview(ctx context.Context, obj *activitypub.Attachment) (*string, error) {
	panic(fmt.Errorf("not implemented: Preview - preview"))
}

// Description is the resolver for the description field.
func (r *attachmentResolver) Description(ctx context.Context, obj *activitypub.Attachment) (*string, error) {
	panic(fmt.Errorf("not implemented: Description - description"))
}

// Blurhash is the resolver for the blurhash field.
func (r *attachmentResolver) Blurhash(ctx context.Context, obj *activitypub.Attachment) (*string, error) {
	panic(fmt.Errorf("not implemented: Blurhash - blurhash"))
}

// Duration is the resolver for the duration field.
func (r *attachmentResolver) Duration(ctx context.Context, obj *activitypub.Attachment) (*float64, error) {
	panic(fmt.Errorf("not implemented: Duration - duration"))
}

// Object is the resolver for the object field.
func (r *moderationDecisionResolver) Object(ctx context.Context, obj *moderation.ModerationDecision) (*model.Object, error) {
	panic(fmt.Errorf("not implemented: Object - object"))
}

// Decision is the resolver for the decision field.
func (r *moderationDecisionResolver) Decision(ctx context.Context, obj *moderation.ModerationDecision) (string, error) {
	panic(fmt.Errorf("not implemented: Decision - decision"))
}

// Confidence is the resolver for the confidence field.
func (r *moderationDecisionResolver) Confidence(ctx context.Context, obj *moderation.ModerationDecision) (float64, error) {
	panic(fmt.Errorf("not implemented: Confidence - confidence"))
}

// Evidence is the resolver for the evidence field.
func (r *moderationDecisionResolver) Evidence(ctx context.Context, obj *moderation.ModerationDecision) ([]string, error) {
	panic(fmt.Errorf("not implemented: Evidence - evidence"))
}

// Reviewers is the resolver for the reviewers field.
func (r *moderationDecisionResolver) Reviewers(ctx context.Context, obj *moderation.ModerationDecision) ([]*activitypub.Actor, error) {
	panic(fmt.Errorf("not implemented: Reviewers - reviewers"))
}

// Timestamp is the resolver for the timestamp field.
func (r *moderationDecisionResolver) Timestamp(ctx context.Context, obj *moderation.ModerationDecision) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: Timestamp - timestamp"))
}

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input model.CreateNoteInput) (*model.CreateNotePayload, error) {
	panic(fmt.Errorf("not implemented: CreateNote - createNote"))
}

// DeleteObject is the resolver for the deleteObject field.
func (r *mutationResolver) DeleteObject(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteObject - deleteObject"))
}

// LikeObject is the resolver for the likeObject field.
func (r *mutationResolver) LikeObject(ctx context.Context, id string) (*activitypub.Activity, error) {
	panic(fmt.Errorf("not implemented: LikeObject - likeObject"))
}

// UnlikeObject is the resolver for the unlikeObject field.
func (r *mutationResolver) UnlikeObject(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnlikeObject - unlikeObject"))
}

// ShareObject is the resolver for the shareObject field.
func (r *mutationResolver) ShareObject(ctx context.Context, id string) (*activitypub.Activity, error) {
	panic(fmt.Errorf("not implemented: ShareObject - shareObject"))
}

// UnshareObject is the resolver for the unshareObject field.
func (r *mutationResolver) UnshareObject(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnshareObject - unshareObject"))
}

// FollowActor is the resolver for the followActor field.
func (r *mutationResolver) FollowActor(ctx context.Context, id string) (*activitypub.Activity, error) {
	panic(fmt.Errorf("not implemented: FollowActor - followActor"))
}

// UnfollowActor is the resolver for the unfollowActor field.
func (r *mutationResolver) UnfollowActor(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnfollowActor - unfollowActor"))
}

// UpdateTrust is the resolver for the updateTrust field.
func (r *mutationResolver) UpdateTrust(ctx context.Context, input model.TrustInput) (*trust.TrustEdge, error) {
	panic(fmt.Errorf("not implemented: UpdateTrust - updateTrust"))
}

// FlagObject is the resolver for the flagObject field.
func (r *mutationResolver) FlagObject(ctx context.Context, input model.FlagInput) (*model.FlagPayload, error) {
	panic(fmt.Errorf("not implemented: FlagObject - flagObject"))
}

// AddCommunityNote is the resolver for the addCommunityNote field.
func (r *mutationResolver) AddCommunityNote(ctx context.Context, input model.CommunityNoteInput) (*model.CommunityNotePayload, error) {
	panic(fmt.Errorf("not implemented: AddCommunityNote - addCommunityNote"))
}

// VoteCommunityNote is the resolver for the voteCommunityNote field.
func (r *mutationResolver) VoteCommunityNote(ctx context.Context, id string, helpful bool) (*model.CommunityNote, error) {
	panic(fmt.Errorf("not implemented: VoteCommunityNote - voteCommunityNote"))
}

// Actor is the resolver for the actor field.
func (r *queryResolver) Actor(ctx context.Context, id *string, username *string) (*activitypub.Actor, error) {
	// Validate input - need either id or username
	if id == nil && username == nil {
		return nil, fmt.Errorf("either id or username must be provided")
	}

	// Track the DynamoDB read
	r.CostTracker.TrackDynamoRead(1)

	// If username is provided, use it (prioritize username over id)
	var actor *activitypub.Actor
	var err error

	if username != nil {
		actor, err = r.Storage.GetActor(ctx, *username)
	} else if id != nil {
		// For id lookups, we'd need to extract username from the id
		// This is a simplified implementation
		username := r.MastodonConv.ExtractUsernameFromActorID(*id)
		if username == "" {
			return nil, fmt.Errorf("invalid actor id format")
		}
		actor, err = r.Storage.GetActor(ctx, username)
	}

	if err != nil {
		r.Logger.Error("Failed to get actor", zap.Error(err))
		return nil, err
	}

	return actor, nil
}

// Object is the resolver for the object field.
func (r *queryResolver) Object(ctx context.Context, id string) (*model.Object, error) {
	panic(fmt.Errorf("not implemented: Object - object"))
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, typeArg model.TimelineType, hashtag *string, listID *string, first *int, after *model.Cursor) (*model.ObjectConnection, error) {
	panic(fmt.Errorf("not implemented: Timeline - timeline"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, typeArg *string, first *int, after *model.Cursor) (*model.ObjectConnection, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// InstanceMetrics is the resolver for the instanceMetrics field.
func (r *queryResolver) InstanceMetrics(ctx context.Context) (*model.InstanceMetrics, error) {
	// Track the DynamoDB operations
	r.CostTracker.TrackDynamoRead(1)

	// For now, return mock data - in production, you'd query actual metrics
	return &model.InstanceMetrics{
		ActiveUsers:          42,
		RequestsPerMinute:    120,
		AverageLatencyMs:     35.5,
		StorageUsedGb:        2.7,
		EstimatedMonthlyCost: 0.89,
		LastUpdated:          model.Time(time.Now()),
	}, nil
}

// CostBreakdown is the resolver for the costBreakdown field.
func (r *queryResolver) CostBreakdown(ctx context.Context, period *model.Period) (*model.CostBreakdown, error) {
	panic(fmt.Errorf("not implemented: CostBreakdown - costBreakdown"))
}

// TrustGraph is the resolver for the trustGraph field.
func (r *queryResolver) TrustGraph(ctx context.Context, actorID string, category *trust.TrustCategory) ([]*trust.TrustEdge, error) {
	panic(fmt.Errorf("not implemented: TrustGraph - trustGraph"))
}

// ModerationQueue is the resolver for the moderationQueue field.
func (r *queryResolver) ModerationQueue(ctx context.Context, first *int, after *model.Cursor) ([]*moderation.ModerationDecision, error) {
	panic(fmt.Errorf("not implemented: ModerationQueue - moderationQueue"))
}

// ExplainObject is the resolver for the explainObject field.
func (r *queryResolver) ExplainObject(ctx context.Context, id string) (*model.ObjectExplanation, error) {
	panic(fmt.Errorf("not implemented: ExplainObject - explainObject"))
}

// FederationStatus is the resolver for the federationStatus field.
func (r *queryResolver) FederationStatus(ctx context.Context, domain string) (*model.FederationStatus, error) {
	panic(fmt.Errorf("not implemented: FederationStatus - federationStatus"))
}

// ActivityStream is the resolver for the activityStream field.
func (r *subscriptionResolver) ActivityStream(ctx context.Context, types []model.ActivityType) (<-chan *activitypub.Activity, error) {
	panic(fmt.Errorf("not implemented: ActivityStream - activityStream"))
}

// TimelineUpdates is the resolver for the timelineUpdates field.
func (r *subscriptionResolver) TimelineUpdates(ctx context.Context, typeArg model.TimelineType) (<-chan *model.Object, error) {
	panic(fmt.Errorf("not implemented: TimelineUpdates - timelineUpdates"))
}

// CostUpdates is the resolver for the costUpdates field.
func (r *subscriptionResolver) CostUpdates(ctx context.Context, threshold *int) (<-chan *model.CostUpdate, error) {
	panic(fmt.Errorf("not implemented: CostUpdates - costUpdates"))
}

// ModerationEvents is the resolver for the moderationEvents field.
func (r *subscriptionResolver) ModerationEvents(ctx context.Context, actorID *string) (<-chan *moderation.ModerationDecision, error) {
	panic(fmt.Errorf("not implemented: ModerationEvents - moderationEvents"))
}

// TrustUpdates is the resolver for the trustUpdates field.
func (r *subscriptionResolver) TrustUpdates(ctx context.Context, actorID string) (<-chan *trust.TrustEdge, error) {
	panic(fmt.Errorf("not implemented: TrustUpdates - trustUpdates"))
}

// URL is the resolver for the url field.
func (r *tagResolver) URL(ctx context.Context, obj *activitypub.Tag) (string, error) {
	panic(fmt.Errorf("not implemented: URL - url"))
}

// From is the resolver for the from field.
func (r *trustEdgeResolver) From(ctx context.Context, obj *trust.TrustEdge) (*activitypub.Actor, error) {
	panic(fmt.Errorf("not implemented: From - from"))
}

// To is the resolver for the to field.
func (r *trustEdgeResolver) To(ctx context.Context, obj *trust.TrustEdge) (*activitypub.Actor, error) {
	panic(fmt.Errorf("not implemented: To - to"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *trustEdgeResolver) UpdatedAt(ctx context.Context, obj *trust.TrustEdge) (*model.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Activity returns ActivityResolver implementation.
func (r *Resolver) Activity() ActivityResolver { return &activityResolver{r} }

// Actor returns ActorResolver implementation.
func (r *Resolver) Actor() ActorResolver { return &actorResolver{r} }

// Attachment returns AttachmentResolver implementation.
func (r *Resolver) Attachment() AttachmentResolver { return &attachmentResolver{r} }

// ModerationDecision returns ModerationDecisionResolver implementation.
func (r *Resolver) ModerationDecision() ModerationDecisionResolver {
	return &moderationDecisionResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Tag returns TagResolver implementation.
func (r *Resolver) Tag() TagResolver { return &tagResolver{r} }

// TrustEdge returns TrustEdgeResolver implementation.
func (r *Resolver) TrustEdge() TrustEdgeResolver { return &trustEdgeResolver{r} }

type activityResolver struct{ *Resolver }
type actorResolver struct{ *Resolver }
type attachmentResolver struct{ *Resolver }
type moderationDecisionResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
type trustEdgeResolver struct{ *Resolver }
