// Package main renders the generated publicsurface section of the security public-surface doc.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/equaltoai/lesser/pkg/auth/publicsurface"
)

const (
	docRelPath  = "docs/security-public-surface.md"
	startMarker = "<!-- BEGIN GENERATED PUBLICSURFACE -->"
	endMarker   = "<!-- END GENERATED PUBLICSURFACE -->"
)

func main() {
	check := flag.Bool("check", false, "fail if the generated publicsurface section is stale")
	flag.Parse()

	repoRoot, err := findRepoRoot()
	if err != nil {
		fatalf("locate repo root: %v", err)
	}
	docPath := filepath.Join(repoRoot, filepath.FromSlash(docRelPath))
	if *check {
		if err := checkDoc(docPath); err != nil {
			fatalf("%v", err)
		}
		return
	}
	if err := updateDoc(docPath); err != nil {
		fatalf("%v", err)
	}
}

func checkDoc(docPath string) error {
	current, err := os.ReadFile(docPath) // #nosec G304 -- repository doc generator.
	if err != nil {
		return fmt.Errorf("read %s: %w", docPath, err)
	}
	updated, changed, err := renderUpdatedDoc(string(current))
	if err != nil {
		return err
	}
	if changed {
		return fmt.Errorf(
			"%s publicsurface section is stale; run `go run ./tools/authsurface_doc`\n\n%s",
			docRelPath,
			firstDiffLine(string(current), updated),
		)
	}
	return nil
}

func updateDoc(docPath string) error {
	current, err := os.ReadFile(docPath) // #nosec G304 -- repository doc generator.
	if err != nil {
		return fmt.Errorf("read %s: %w", docPath, err)
	}
	updated, changed, err := renderUpdatedDoc(string(current))
	if err != nil {
		return err
	}
	if !changed {
		return nil
	}
	if err := os.WriteFile(docPath, []byte(updated), 0o600); err != nil { // #nosec G306,G703 -- repository doc output path is resolved from repo root.
		return fmt.Errorf("write %s: %w", docPath, err)
	}
	return nil
}

func renderUpdatedDoc(current string) (string, bool, error) {
	start := strings.Index(current, startMarker)
	if start < 0 {
		return "", false, fmt.Errorf("missing %q marker", startMarker)
	}
	end := strings.Index(current, endMarker)
	if end < 0 {
		return "", false, fmt.Errorf("missing %q marker", endMarker)
	}
	if end < start {
		return "", false, errors.New("generated publicsurface markers are out of order")
	}

	end += len(endMarker)
	generated := renderGeneratedSection()
	updated := current[:start] + generated + current[end:]
	return updated, updated != current, nil
}

func renderGeneratedSection() string {
	var buf bytes.Buffer
	buf.WriteString(startMarker)
	buf.WriteString("\n")
	buf.WriteString("<!-- Code generated by `go run ./tools/authsurface_doc`; DO NOT EDIT THIS SECTION. -->\n\n")
	buf.WriteString("#### Anonymous public rules from `pkg/auth/publicsurface`\n\n")
	buf.WriteString("| Methods | Match | Path/prefix | Notes |\n")
	buf.WriteString("| --- | --- | --- | --- |\n")
	for _, rule := range publicsurface.PublicRules() {
		buf.WriteString("| ")
		buf.WriteString(markdownEscape(strings.Join(rule.Methods, "/")))
		buf.WriteString(" | ")
		buf.WriteString(markdownEscape(string(rule.Match)))
		buf.WriteString(" | `")
		buf.WriteString(markdownCodeEscape(rule.Path))
		buf.WriteString("` | ")
		buf.WriteString(markdownEscape(ruleNotes(rule)))
		buf.WriteString(" |\n")
	}

	buf.WriteString("\n")
	buf.WriteString("#### Handler-enforced ContractAuth classes\n\n")
	buf.WriteString("These routes are intentionally gate-reachable but are **not** anonymous in the generated contract. ")
	buf.WriteString("Handlers enforce the listed auth class; the gate-level backstop remains optional defense-in-depth.\n\n")
	buf.WriteString("| Method | Path | Contract auth class | Notes |\n")
	buf.WriteString("| --- | --- | --- | --- |\n")
	for _, rule := range publicsurface.ContractAuthRules() {
		buf.WriteString("| ")
		buf.WriteString(markdownEscape(rule.Method))
		buf.WriteString(" | `")
		buf.WriteString(markdownCodeEscape(rule.Path))
		buf.WriteString("` | `")
		buf.WriteString(markdownCodeEscape(string(rule.Class)))
		buf.WriteString("` | ")
		buf.WriteString(markdownEscape(rule.Description))
		buf.WriteString(" |\n")
	}
	buf.WriteString(endMarker)
	return buf.String()
}

func ruleNotes(rule publicsurface.PublicRule) string {
	parts := []string{rule.Description}
	if len(rule.ExceptExactPaths) > 0 {
		parts = append(parts, "excludes exact "+joinCode(rule.ExceptExactPaths))
	}
	if len(rule.ExceptSuffixes) > 0 {
		parts = append(parts, "excludes suffix "+joinCode(rule.ExceptSuffixes))
	}
	if len(rule.RequiredContains) > 0 {
		parts = append(parts, "requires path segment "+joinCode(rule.RequiredContains))
	}
	return strings.Join(parts, "; ")
}

func joinCode(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = "`" + markdownCodeEscape(value) + "`"
	}
	return strings.Join(quoted, ", ")
}

func markdownEscape(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}

func markdownCodeEscape(value string) string {
	return strings.ReplaceAll(value, "`", "\\`")
}

func firstDiffLine(before, after string) string {
	beforeLines := strings.Split(before, "\n")
	afterLines := strings.Split(after, "\n")
	maxLen := len(beforeLines)
	if len(afterLines) > maxLen {
		maxLen = len(afterLines)
	}
	for i := 0; i < maxLen; i++ {
		var beforeLine, afterLine string
		if i < len(beforeLines) {
			beforeLine = beforeLines[i]
		}
		if i < len(afterLines) {
			afterLine = afterLines[i]
		}
		if beforeLine != afterLine {
			return fmt.Sprintf("first difference at line %d:\n- %s\n+ %s", i+1, beforeLine, afterLine)
		}
	}
	return "contents differ"
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			if _, err := os.Stat(filepath.Join(dir, docRelPath)); err == nil {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found")
		}
		dir = parent
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
