// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/aron23/lesser/pkg/activitypub"
	"github.com/aron23/lesser/pkg/trust"
)

type AccessLog struct {
	Timestamp Time   `json:"timestamp"`
	Operation string `json:"operation"`
	Cost      int    `json:"cost"`
}

type CommunityNote struct {
	ID         string             `json:"id"`
	Author     *activitypub.Actor `json:"author"`
	Content    string             `json:"content"`
	Helpful    int                `json:"helpful"`
	NotHelpful int                `json:"notHelpful"`
	CreatedAt  Time               `json:"createdAt"`
}

type CommunityNoteInput struct {
	ObjectID string `json:"objectId"`
	Content  string `json:"content"`
}

type CommunityNotePayload struct {
	Note   *CommunityNote `json:"note"`
	Object *Object        `json:"object"`
}

type ContentMap struct {
	Language string `json:"language"`
	Content  string `json:"content"`
}

type ContentMapInput struct {
	Language string `json:"language"`
	Content  string `json:"content"`
}

type CostBreakdown struct {
	Period           Period      `json:"period"`
	TotalCost        float64     `json:"totalCost"`
	DynamoDBCost     float64     `json:"dynamoDBCost"`
	S3StorageCost    float64     `json:"s3StorageCost"`
	LambdaCost       float64     `json:"lambdaCost"`
	DataTransferCost float64     `json:"dataTransferCost"`
	Breakdown        []*CostItem `json:"breakdown"`
}

type CostItem struct {
	Operation string  `json:"operation"`
	Count     int     `json:"count"`
	Cost      float64 `json:"cost"`
}

type CostUpdate struct {
	OperationCost     int     `json:"operationCost"`
	DailyTotal        float64 `json:"dailyTotal"`
	MonthlyProjection float64 `json:"monthlyProjection"`
}

type CreateNoteInput struct {
	Content       string             `json:"content"`
	ContentMap    []*ContentMapInput `json:"contentMap,omitempty"`
	InReplyToID   *string            `json:"inReplyToId,omitempty"`
	Visibility    Visibility         `json:"visibility"`
	Sensitive     *bool              `json:"sensitive,omitempty"`
	SpoilerText   *string            `json:"spoilerText,omitempty"`
	AttachmentIds []string           `json:"attachmentIds,omitempty"`
	Mentions      []string           `json:"mentions,omitempty"`
	Tags          []string           `json:"tags,omitempty"`
}

type CreateNotePayload struct {
	Object   *Object               `json:"object"`
	Activity *activitypub.Activity `json:"activity"`
	Cost     *CostUpdate           `json:"cost"`
}

type FederationStatus struct {
	Domain      string  `json:"domain"`
	Reachable   bool    `json:"reachable"`
	LastContact *Time   `json:"lastContact,omitempty"`
	SharedInbox *string `json:"sharedInbox,omitempty"`
	PublicKey   *string `json:"publicKey,omitempty"`
	Software    *string `json:"software,omitempty"`
	Version     *string `json:"version,omitempty"`
}

type Field struct {
	Name       string `json:"name"`
	Value      string `json:"value"`
	VerifiedAt *Time  `json:"verifiedAt,omitempty"`
}

type FlagInput struct {
	ObjectID string   `json:"objectId"`
	Reason   string   `json:"reason"`
	Evidence []string `json:"evidence,omitempty"`
}

type FlagPayload struct {
	ModerationID string `json:"moderationId"`
	Queued       bool   `json:"queued"`
}

type InstanceMetrics struct {
	ActiveUsers          int     `json:"activeUsers"`
	RequestsPerMinute    int     `json:"requestsPerMinute"`
	AverageLatencyMs     float64 `json:"averageLatencyMs"`
	StorageUsedGb        float64 `json:"storageUsedGB"`
	EstimatedMonthlyCost float64 `json:"estimatedMonthlyCost"`
	LastUpdated          Time    `json:"lastUpdated"`
}

type Mention struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Domain   *string `json:"domain,omitempty"`
	URL      string  `json:"url"`
}

type Mutation struct {
}

type Object struct {
	ID              string                    `json:"id"`
	Type            ObjectType                `json:"type"`
	Actor           *activitypub.Actor        `json:"actor"`
	Content         string                    `json:"content"`
	ContentMap      []*ContentMap             `json:"contentMap"`
	InReplyTo       *Object                   `json:"inReplyTo,omitempty"`
	Visibility      Visibility                `json:"visibility"`
	Sensitive       bool                      `json:"sensitive"`
	SpoilerText     *string                   `json:"spoilerText,omitempty"`
	Attachments     []*activitypub.Attachment `json:"attachments"`
	Tags            []*activitypub.Tag        `json:"tags"`
	Mentions        []*Mention                `json:"mentions"`
	CreatedAt       Time                      `json:"createdAt"`
	UpdatedAt       Time                      `json:"updatedAt"`
	RepliesCount    int                       `json:"repliesCount"`
	LikesCount      int                       `json:"likesCount"`
	SharesCount     int                       `json:"sharesCount"`
	EstimatedCost   int                       `json:"estimatedCost"`
	ModerationScore *float64                  `json:"moderationScore,omitempty"`
	CommunityNotes  []*CommunityNote          `json:"communityNotes"`
}

type ObjectConnection struct {
	Edges      []*ObjectEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type ObjectEdge struct {
	Node   *Object `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

type ObjectExplanation struct {
	Object          *Object      `json:"object"`
	StorageLocation string       `json:"storageLocation"`
	SizeBytes       int          `json:"sizeBytes"`
	StorageCost     float64      `json:"storageCost"`
	AccessPattern   []*AccessLog `json:"accessPattern"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor,omitempty"`
	EndCursor       *Cursor `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type TrustInput struct {
	TargetActorID string              `json:"targetActorId"`
	Category      trust.TrustCategory `json:"category"`
	Score         float64             `json:"score"`
}

type ActivityType string

const (
	ActivityTypeCreate   ActivityType = "CREATE"
	ActivityTypeUpdate   ActivityType = "UPDATE"
	ActivityTypeDelete   ActivityType = "DELETE"
	ActivityTypeFollow   ActivityType = "FOLLOW"
	ActivityTypeLike     ActivityType = "LIKE"
	ActivityTypeAnnounce ActivityType = "ANNOUNCE"
	ActivityTypeUndo     ActivityType = "UNDO"
	ActivityTypeAccept   ActivityType = "ACCEPT"
	ActivityTypeReject   ActivityType = "REJECT"
	ActivityTypeFlag     ActivityType = "FLAG"
)

var AllActivityType = []ActivityType{
	ActivityTypeCreate,
	ActivityTypeUpdate,
	ActivityTypeDelete,
	ActivityTypeFollow,
	ActivityTypeLike,
	ActivityTypeAnnounce,
	ActivityTypeUndo,
	ActivityTypeAccept,
	ActivityTypeReject,
	ActivityTypeFlag,
}

func (e ActivityType) IsValid() bool {
	switch e {
	case ActivityTypeCreate, ActivityTypeUpdate, ActivityTypeDelete, ActivityTypeFollow, ActivityTypeLike, ActivityTypeAnnounce, ActivityTypeUndo, ActivityTypeAccept, ActivityTypeReject, ActivityTypeFlag:
		return true
	}
	return false
}

func (e ActivityType) String() string {
	return string(e)
}

func (e *ActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityType", str)
	}
	return nil
}

func (e ActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ActorType string

const (
	ActorTypePerson       ActorType = "PERSON"
	ActorTypeGroup        ActorType = "GROUP"
	ActorTypeApplication  ActorType = "APPLICATION"
	ActorTypeService      ActorType = "SERVICE"
	ActorTypeOrganization ActorType = "ORGANIZATION"
)

var AllActorType = []ActorType{
	ActorTypePerson,
	ActorTypeGroup,
	ActorTypeApplication,
	ActorTypeService,
	ActorTypeOrganization,
}

func (e ActorType) IsValid() bool {
	switch e {
	case ActorTypePerson, ActorTypeGroup, ActorTypeApplication, ActorTypeService, ActorTypeOrganization:
		return true
	}
	return false
}

func (e ActorType) String() string {
	return string(e)
}

func (e *ActorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActorType", str)
	}
	return nil
}

func (e ActorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActorType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActorType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ObjectType string

const (
	ObjectTypeNote     ObjectType = "NOTE"
	ObjectTypeArticle  ObjectType = "ARTICLE"
	ObjectTypeImage    ObjectType = "IMAGE"
	ObjectTypeVideo    ObjectType = "VIDEO"
	ObjectTypeQuestion ObjectType = "QUESTION"
	ObjectTypeEvent    ObjectType = "EVENT"
	ObjectTypePage     ObjectType = "PAGE"
)

var AllObjectType = []ObjectType{
	ObjectTypeNote,
	ObjectTypeArticle,
	ObjectTypeImage,
	ObjectTypeVideo,
	ObjectTypeQuestion,
	ObjectTypeEvent,
	ObjectTypePage,
}

func (e ObjectType) IsValid() bool {
	switch e {
	case ObjectTypeNote, ObjectTypeArticle, ObjectTypeImage, ObjectTypeVideo, ObjectTypeQuestion, ObjectTypeEvent, ObjectTypePage:
		return true
	}
	return false
}

func (e ObjectType) String() string {
	return string(e)
}

func (e *ObjectType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ObjectType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ObjectType", str)
	}
	return nil
}

func (e ObjectType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ObjectType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ObjectType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Period string

const (
	PeriodHour  Period = "HOUR"
	PeriodDay   Period = "DAY"
	PeriodWeek  Period = "WEEK"
	PeriodMonth Period = "MONTH"
	PeriodYear  Period = "YEAR"
)

var AllPeriod = []Period{
	PeriodHour,
	PeriodDay,
	PeriodWeek,
	PeriodMonth,
	PeriodYear,
}

func (e Period) IsValid() bool {
	switch e {
	case PeriodHour, PeriodDay, PeriodWeek, PeriodMonth, PeriodYear:
		return true
	}
	return false
}

func (e Period) String() string {
	return string(e)
}

func (e *Period) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Period(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Period", str)
	}
	return nil
}

func (e Period) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Period) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Period) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimelineType string

const (
	TimelineTypeHome    TimelineType = "HOME"
	TimelineTypePublic  TimelineType = "PUBLIC"
	TimelineTypeLocal   TimelineType = "LOCAL"
	TimelineTypeHashtag TimelineType = "HASHTAG"
	TimelineTypeList    TimelineType = "LIST"
	TimelineTypeDirect  TimelineType = "DIRECT"
)

var AllTimelineType = []TimelineType{
	TimelineTypeHome,
	TimelineTypePublic,
	TimelineTypeLocal,
	TimelineTypeHashtag,
	TimelineTypeList,
	TimelineTypeDirect,
}

func (e TimelineType) IsValid() bool {
	switch e {
	case TimelineTypeHome, TimelineTypePublic, TimelineTypeLocal, TimelineTypeHashtag, TimelineTypeList, TimelineTypeDirect:
		return true
	}
	return false
}

func (e TimelineType) String() string {
	return string(e)
}

func (e *TimelineType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimelineType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimelineType", str)
	}
	return nil
}

func (e TimelineType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimelineType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimelineType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Visibility string

const (
	VisibilityPublic    Visibility = "PUBLIC"
	VisibilityUnlisted  Visibility = "UNLISTED"
	VisibilityFollowers Visibility = "FOLLOWERS"
	VisibilityDirect    Visibility = "DIRECT"
)

var AllVisibility = []Visibility{
	VisibilityPublic,
	VisibilityUnlisted,
	VisibilityFollowers,
	VisibilityDirect,
}

func (e Visibility) IsValid() bool {
	switch e {
	case VisibilityPublic, VisibilityUnlisted, VisibilityFollowers, VisibilityDirect:
		return true
	}
	return false
}

func (e Visibility) String() string {
	return string(e)
}

func (e *Visibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Visibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Visibility", str)
	}
	return nil
}

func (e Visibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Visibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Visibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
