package auth

import "strings"

// commonPasswordsList contains a comprehensive list of common passwords
// This list is based on common password lists and breach databases
var commonPasswordsList = map[string]bool{
	// Top 100 most common passwords from various breaches
	"123456":      true,
	"123456789":   true,
	"12345":       true,
	"qwerty":      true,
	"password":    true,
	"12345678":    true,
	"111111":      true,
	"123123":      true,
	"1234567890":  true,
	"1234567":     true,
	"qwerty123":   true,
	"000000":      true,
	"1q2w3e":      true,
	"aa12345678":  true,
	"abc123":      true,
	"password1":   true,
	"password123": true,
	"1234":        true,
	"qwertyuiop":  true,
	"123321":      true,
	"password!":   true,
	"iloveyou":    true,
	"welcome":     true,
	"monkey":      true,
	"dragon":      true,
	"sunshine":    true,
	"princess":    true,
	"football":    true,
	"baseball":    true,
	"master":      true,
	"michael":     true,
	"shadow":      true,
	"superman":    true,
	"batman":      true,
	"trustno1":    true,
	"hello":       true,
	"charlie":     true,
	"access":      true,
	"freedom":     true,
	"thunder":     true,
	"mustang":     true,
	"jordan":      true,
	"jennifer":    true,
	"hunter":      true,
	"michelle":    true,
	"diamond":     true,
	"silver":      true,
	"daniel":      true,
	"maggie":      true,
	"buster":      true,
	"pepper":      true,
	"ginger":      true,
	"summer":      true,
	"taylor":      true,
	"ashley":      true,
	"chelsea":     true,
	"ranger":      true,
	"dallas":      true,
	"donald":      true,

	// Common patterns with years
	"password2023": true,
	"password2024": true,
	"password2022": true,
	"password2021": true,
	"password2020": true,
	"qwerty2023":   true,
	"qwerty2024":   true,
	"welcome2023":  true,
	"welcome2024":  true,
	"admin2023":    true,
	"admin2024":    true,

	// Common with special characters
	"password@123": true,
	"password!123": true,
	"password#123": true,
	"password$123": true,
	"p@ssw0rd":     true,
	"p@ssword":     true,
	"passw0rd":     true,
	"pa$$word":     true,
	"pa$$w0rd":     true,
	"qwerty!@#":    true,
	"qwerty123!":   true,
	"admin@123":    true,
	"admin!123":    true,
	"admin#123":    true,
	"welcome@123":  true,
	"welcome!123":  true,
	"test@123":     true,
	"test!123":     true,
	"demo@123":     true,
	"demo!123":     true,
	"root@123":     true,
	"user@123":     true,
	"guest@123":    true,

	// Keyboard patterns
	"qwertyui":     true,
	"qwerty12":     true,
	"qwerty123456": true,
	"qazwsx":       true,
	"qazwsxedc":    true,
	"zxcvbnm":      true,
	"asdfghjkl":    true,
	"1qaz2wsx":     true,
	"1qazxsw2":     true,
	"!qaz2wsx":     true,
	"qweasd":       true,
	"qweasdzxc":    true,

	// Common names as passwords
	"alexander":     true,
	"password1234":  true,
	"password12345": true,
	"computer":      true,
	"internet":      true,
	"security":      true,
	"letmein":       true,
	"letmein123":    true,
	"superman123":   true,
	"batman123":     true,
	"monkey123":     true,
	"dragon123":     true,
	"master123":     true,
	"login":         true,
	"welcome123":    true,
	"hello123":      true,
	"whatever":      true,
	"starwars":      true,
	"matrix":        true,
	"ironman":       true,
	"avengers":      true,
	"marvel":        true,
	"asshole":       true,
	"secret":        true,
	"password1!":    true,
	"password123!":  true,
	"admin1234":     true,
	"administrator": true,
	"root1234":      true,
	"rootroot":      true,
	"toor":          true,
	"pass":          true,
	"pass123":       true,
	"pass1234":      true,
	"passwd":        true,
	"changeme":      true,
	"changeme123":   true,
	"default":       true,
	"default123":    true,
	"guest":         true,
	"guest123":      true,
	"user":          true,
	"user123":       true,
	"user1234":      true,
	"admin":         true,
	"nimda":         true,
	"god":           true,
	"love":          true,
	"sex":           true,
	"secret123":     true,
	"qwe123":        true,
	"zxc123":        true,
	"asd123":        true,
	"123qwe":        true,
	"123asd":        true,
	"123zxc":        true,
	"1q2w3e4r":      true,
	"1q2w3e4r5t":    true,
	"q1w2e3r4":      true,
	"q1w2e3r4t5":    true,

	// Service-specific common passwords
	"facebook":  true,
	"twitter":   true,
	"google":    true,
	"youtube":   true,
	"instagram": true,
	"linkedin":  true,
	"microsoft": true,
	"apple":     true,
	"samsung":   true,
	"amazon":    true,

	// More number patterns
	"000000000":       true,
	"111111111":       true,
	"123456789012345": true,
	"12341234":        true,
	"00000000":        true,
	"11111111":        true,
	"22222222":        true,
	"88888888":        true,
	"99999999":        true,
	"87654321":        true,
	"11223344":        true,
	"112233":          true,
	"123123123":       true,
	"666666":          true,
	"696969":          true,
	"12345678910":     true,
	"asdf1234":        true,
	"password12":      true,
	"password0":       true,
	"password01":      true,
	"password11":      true,
	"password99":      true,
	"pass12345":       true,
	"passpass":        true,
	"admin123456":     true,
}

// IsCommonPassword checks if a password is in the common passwords list
func IsCommonPassword(password string) bool {
	// Check exact match (case-insensitive)
	return commonPasswordsList[password] || commonPasswordsList[strings.ToLower(password)]
}
