#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CORE="$ROOT_DIR/graph/core.graphql"
PHASE1="$ROOT_DIR/graph/phase1.graphql"
PHASE2="$ROOT_DIR/graph/phase2.graphql"
PHASE3="$ROOT_DIR/graph/phase3.graphql"
AGENTS="$ROOT_DIR/graph/agents.graphql"
OUTPUT="$ROOT_DIR/docs/contracts/graphql-schema.graphql"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out|-o)
      if [[ $# -lt 2 ]]; then
        echo "Error: --out requires a path" >&2
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    *)
      echo "Error: unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$CORE" ]]; then
  echo "Core schema not found at $CORE" >&2
  exit 1
fi

if [[ ! -f "$PHASE1" ]]; then
  echo "Phase 1 schema not found at $PHASE1" >&2
  exit 1
fi

if [[ ! -f "$PHASE2" ]]; then
  echo "Phase 2 schema not found at $PHASE2" >&2
  exit 1
fi

if [[ ! -f "$PHASE3" ]]; then
  echo "Phase 3 schema not found at $PHASE3" >&2
  exit 1
fi

if [[ ! -f "$AGENTS" ]]; then
  echo "Agents schema not found at $AGENTS" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

{
  echo "# DO NOT EDIT: aggregated schema for client consumption"
  echo "# Generated by scripts/generate_schema.sh"
  echo
  cat "$CORE"
  echo
  cat "$PHASE1"
  echo
  cat "$PHASE2"
  echo
  cat "$PHASE3"
  echo
  cat "$AGENTS"
} > "$OUTPUT"

echo "Wrote aggregated schema to $OUTPUT"
